"""Emit handlers, keyboards, main.py registration for generated bots."""
from __future__ import annotations

from ..coding_emit_foundation import _msg
from ..registry import get_capability
from ..schema import BotSpec, Feature

def _emit_requirements() -> str:
    return (
        "python-telegram-bot>=22.8,<23\n"
        "python-dotenv>=1.2.2\n"
    )


def _emit_env() -> str:
    return (
        "TELEGRAM_BOT_TOKEN=\n"
        "PAYMENT_PROVIDER_TOKEN=\n"
        "ADMIN_USER_IDS=\n"
        "DEFAULT_CURRENCY=USD\n"
    )



def _emit_readme(spec: BotSpec) -> str:
    return f"""# {spec.bot.name}

Generated by **spec_core** (zero-AI deterministic engine).

## Run

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
# put TELEGRAM_BOT_TOKEN in .env
python main.py
```

## Features

{chr(10).join(f"- `{f.feature}` via {f.trigger.type}:{f.trigger.id}" for f in spec.features)}
"""



