"""
Environment Generator — Specification 065.

Writes .env into the generated project. The token value is written to
.env only (gitignored runtime config) and never logged.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, Optional

_log = logging.getLogger("engine.live_deployment.env_gen")


class EnvironmentGenerator:
    """Create / update .env for a generated project."""

    def write_env(
        self,
        project_path: str | Path,
        *,
        bot_token: str,
        extra: Optional[Dict[str, str]] = None,
    ) -> bool:
        project_path = Path(project_path)
        if not project_path.exists():
            _log.error("Project path does not exist for .env write")
            return False

        env_path = project_path / ".env"
        lines = [
            "# Auto-generated by Live Deployment Engine — do not commit",
            f"BOT_TOKEN={bot_token}",
        ]
        extra = extra or {}
        for key, value in extra.items():
            if key.upper() == "BOT_TOKEN":
                continue
            lines.append(f"{key}={value}")

        try:
            env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            # Ensure .gitignore contains .env
            gi = project_path / ".gitignore"
            if gi.exists():
                text = gi.read_text(encoding="utf-8", errors="replace")
                if ".env" not in text.splitlines() and ".env" not in text:
                    gi.write_text(text.rstrip() + "\n.env\n", encoding="utf-8")
            else:
                gi.write_text(".env\n__pycache__/\n*.pyc\n", encoding="utf-8")
            _log.info("Wrote .env for project", extra={"path": str(project_path)})
            return True
        except Exception as e:
            _log.error("Failed to write .env", extra={"error": type(e).__name__})
            return False
