"""
Complete bot templates – generate real handlers from FormalBotSpec.
"""

from __future__ import annotations

import re

from ..schemas.formal_spec import FormalBotSpec


def render_requirements(spec: FormalBotSpec) -> str:
    deps = [
        "python-telegram-bot>=21.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0",
        "pydantic-settings>=2.0",
    ]
    if spec.database.value == "postgres":
        deps.extend(["asyncpg>=0.29.0", "sqlalchemy[asyncio]>=2.0"])
    else:
        deps.append("aiosqlite>=0.20.0")
    if spec.requires_async_queue:
        deps.extend(["arq>=0.26.0", "redis>=5.0"])
    if spec.requires_payments:
        deps.append("stripe>=8.0")
    return "\n".join(sorted(set(deps))) + "\n"


def render_env_example(spec: FormalBotSpec) -> str:
    lines = [
        "TELEGRAM_BOT_TOKEN=your-bot-token-here",
        "ALLOWED_USER_IDS=",
        f"BOT_NAME={spec.bot_name}",
        "ADMIN_USER_IDS=",
        "LOG_LEVEL=INFO",
        "",
    ]
    if spec.database.value == "postgres":
        lines += ["DATABASE_URL=postgresql+asyncpg://user:pass@localhost:5432/botdb", ""]
    if spec.requires_async_queue:
        lines += ["REDIS_URL=redis://localhost:6379/0", ""]
    if spec.requires_payments:
        lines += ["STRIPE_SECRET_KEY=", "STRIPE_WEBHOOK_SECRET=", ""]
    return "\n".join(lines)


def render_config(spec: FormalBotSpec) -> str:
    return f'''"""Application configuration – strict & typed."""
from __future__ import annotations
from functools import lru_cache
from typing import Set
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")
    telegram_bot_token: str = Field(..., min_length=30)
    allowed_user_ids: str = ""
    admin_user_ids: str = ""
    bot_name: str = "{spec.bot_name}"
    log_level: str = "INFO"
    database_url: str | None = None
    redis_url: str | None = None

    @field_validator("allowed_user_ids", "admin_user_ids", mode="before")
    @classmethod
    def _parse(cls, v: object) -> str:
        return "" if v is None else str(v)

    def _ids(self, raw: str) -> Set[int]:
        if not raw.strip():
            return set()
        return {{int(x.strip()) for x in raw.split(",") if x.strip().isdigit()}}

    @property
    def allowed_ids(self) -> Set[int]:
        return self._ids(self.allowed_user_ids)

    @property
    def admin_ids(self) -> Set[int]:
        return self._ids(self.admin_user_ids)

@lru_cache
def get_settings() -> Settings:
    return Settings()
'''


def _cmd_handlers_imports(spec: FormalBotSpec) -> str:
    cmds = [c.command for c in spec.ui.commands]
    lines = ["from app.handlers.start import start_handler, help_handler"]
    if "products" in cmds or spec.bot_type.value == "ecommerce":
        lines.append("from app.handlers.products import products_handler")
    if "cart" in cmds or spec.bot_type.value == "ecommerce":
        lines.append("from app.handlers.cart import cart_handler")
    if "orders" in cmds or spec.bot_type.value == "ecommerce":
        lines.append("from app.handlers.orders import orders_handler")
    if "admin" in cmds or spec.requires_admin_panel:
        lines.append("from app.handlers.admin import admin_handler")
    lines.append("from app.handlers.callbacks import callback_handler")
    lines.append("from app.handlers.messages import message_handler")
    return "\n".join(lines)


def _cmd_registrations(spec: FormalBotSpec) -> str:
    lines = [
        '    app.add_handler(CommandHandler("start", start_handler))',
        '    app.add_handler(CommandHandler("help", help_handler))',
    ]
    cmds = {c.command for c in spec.ui.commands}
    if "products" in cmds or spec.bot_type.value == "ecommerce":
        lines.append('    app.add_handler(CommandHandler("products", products_handler))')
    if "cart" in cmds or spec.bot_type.value == "ecommerce":
        lines.append('    app.add_handler(CommandHandler("cart", cart_handler))')
    if "orders" in cmds or spec.bot_type.value == "ecommerce":
        lines.append('    app.add_handler(CommandHandler("orders", orders_handler))')
    if "admin" in cmds or spec.requires_admin_panel:
        lines.append('    app.add_handler(CommandHandler("admin", admin_handler))')
    # register any other custom commands generically via messages for now
    lines.append("    app.add_handler(CallbackQueryHandler(callback_handler))")
    lines.append("    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, message_handler))")
    return "\n".join(lines)


def render_main(spec: FormalBotSpec) -> str:
    safe = re.sub(r"[^a-z0-9_]", "_", spec.bot_name.lower())
    return f'''"""
{spec.bot_name} – Telegram Bot
Generated by Formal Bot Engine.
"""
from __future__ import annotations
import logging
import sys
from telegram import Update
from telegram.ext import Application, CallbackQueryHandler, CommandHandler, MessageHandler, filters
from app.config import get_settings
{_cmd_handlers_imports(spec)}

logging.basicConfig(
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    level=logging.INFO,
    stream=sys.stdout,
)
logger = logging.getLogger("{safe}")


def build_application() -> Application:
    settings = get_settings()
    app = Application.builder().token(settings.telegram_bot_token).build()
{_cmd_registrations(spec)}
    return app


def main() -> None:
    logger.info("Starting %s ...", "{spec.bot_name}")
    application = build_application()
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
'''


def render_start_handler(spec: FormalBotSpec) -> str:
    rows = []
    for b in (spec.ui.main_buttons or [])[:8]:
        text = b.text.replace("\\", "\\\\").replace('"', '\\"')
        cb = b.callback_data.replace('"', '\\"')
        rows.append(f'        [InlineKeyboardButton("{text}", callback_data="{cb}")]' )
    if not rows:
        rows = ['        [InlineKeyboardButton("🏠 القائمة", callback_data="main_menu")]']
    buttons_code = ",\n".join(rows)
    welcome = (spec.ui.welcome_message or ("مرحبا بك في " + spec.bot_name))
    welcome = welcome.replace('"""', "'''")
    cmd_lines = "\\n".join(f"/{c.command} — {c.description}" for c in spec.ui.commands) or "/start — تشغيل"
    return (
        '"""Start / help handlers with main menu buttons."""\n'
        "from __future__ import annotations\n"
        "from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update\n"
        "from telegram.constants import ParseMode\n"
        "from telegram.ext import ContextTypes\n\n\n"
        "def _main_keyboard() -> InlineKeyboardMarkup:\n"
        "    keyboard = [\n"
        + buttons_code + "\n"
        "    ]\n"
        "    return InlineKeyboardMarkup(keyboard)\n\n\n"
        "async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:\n"
        "    message = update.effective_message\n"
        "    if message is None:\n"
        "        return\n"
        "    text = " + repr(welcome) + "\n"
        "    await message.reply_text(text, parse_mode=ParseMode.MARKDOWN, reply_markup=_main_keyboard())\n\n\n"
        "async def help_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:\n"
        "    message = update.effective_message\n"
        "    if message is None:\n"
        "        return\n"
        "    text = " + repr("*الأوامر المتاحة:*\n" + cmd_lines.replace("\\n", "\n")) + "\n"
        "    await message.reply_text(text, parse_mode=ParseMode.MARKDOWN, reply_markup=_main_keyboard())\n"
    )


def render_products_handler(spec: FormalBotSpec) -> str:
    return '''"""Products catalog handler."""
from __future__ import annotations
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import ContextTypes
from app.services.catalog import CatalogService

async def products_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None:
        return
    catalog = CatalogService()
    products = catalog.list_products()
    if not products:
        await message.reply_text("لا توجد منتجات حالياً.")
        return
    lines = ["*كتالوج المنتجات:*\\n"]
    keyboard = []
    for p in products:
        lines.append(f"• *{p['name']}* — {p['price']} ج.م")
        keyboard.append([
            InlineKeyboardButton(
                f"أضف للسلة: {p['name']}",
                callback_data=f"add_cart:{p['id']}",
            )
        ])
    keyboard.append([InlineKeyboardButton("🧺 السلة", callback_data="cart")])
    await message.reply_text(
        "\\n".join(lines),
        parse_mode="Markdown",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )
'''


def render_cart_handler(spec: FormalBotSpec) -> str:
    return '''"""Shopping cart handler."""
from __future__ import annotations
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import ContextTypes
from app.services.cart import CartService

async def cart_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None:
        return
    user = update.effective_user
    uid = user.id if user else 0
    cart = CartService()
    items = cart.get_items(uid)
    if not items:
        await message.reply_text("السلة فارغة. تصفح المنتجات عبر /products")
        return
    lines = ["*سلتك:*\\n"]
    total = 0
    for it in items:
        lines.append(f"• {it['name']} x{it['qty']} = {it['price'] * it['qty']} ج.م")
        total += it["price"] * it["qty"]
    lines.append(f"\\n*الإجمالي:* {total} ج.م")
    keyboard = [
        [InlineKeyboardButton("✅ إتمام الطلب", callback_data="checkout")],
        [InlineKeyboardButton("🗑 تفريغ السلة", callback_data="clear_cart")],
        [InlineKeyboardButton("🛒 المنتجات", callback_data="products")],
    ]
    await message.reply_text(
        "\\n".join(lines),
        parse_mode="Markdown",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )
'''


def render_orders_handler(spec: FormalBotSpec) -> str:
    return '''"""User orders handler."""
from __future__ import annotations
from telegram import Update
from telegram.ext import ContextTypes
from app.services.orders import OrderService

async def orders_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None:
        return
    user = update.effective_user
    uid = user.id if user else 0
    svc = OrderService()
    orders = svc.list_user_orders(uid)
    if not orders:
        await message.reply_text("لا توجد طلبات بعد.")
        return
    lines = ["*طلباتك:*\\n"]
    for o in orders:
        lines.append(f"• #{o['id']} — {o['status']} — {o['total']} ج.م")
    await message.reply_text("\\n".join(lines), parse_mode="Markdown")
'''


def render_admin_handler(spec: FormalBotSpec) -> str:
    return '''"""Admin panel handler."""
from __future__ import annotations
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import ContextTypes
from app.config import get_settings

async def admin_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    user = update.effective_user
    if message is None or user is None:
        return
    settings = get_settings()
    if settings.admin_ids and user.id not in settings.admin_ids:
        await message.reply_text("⛔ غير مصرح — للأدمن فقط.")
        return
    keyboard = [
        [InlineKeyboardButton("📦 إدارة المنتجات", callback_data="admin_products")],
        [InlineKeyboardButton("📋 الطلبات الجديدة", callback_data="admin_orders")],
        [InlineKeyboardButton("📊 إحصائيات", callback_data="admin_stats")],
    ]
    await message.reply_text(
        "*لوحة الإدارة*\\nاختر قسماً:",
        parse_mode="Markdown",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )
'''


def render_callback_handler(spec: FormalBotSpec) -> str:
    return '''"""Callback query router for all inline buttons."""
from __future__ import annotations
from telegram import Update
from telegram.ext import ContextTypes
from app.handlers.products import products_handler
from app.handlers.cart import cart_handler
from app.services.cart import CartService
from app.services.orders import OrderService
from app.services.catalog import CatalogService

async def callback_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    if query is None:
        return
    await query.answer()
    data = query.data or ""
    user = update.effective_user
    uid = user.id if user else 0

    if data in ("products", "المنتجات") or "منتج" in data:
        # reuse products flow via fake message path
        if query.message:
            await query.edit_message_text("جاري عرض المنتجات...")
        # send products
        catalog = CatalogService()
        products = catalog.list_products()
        lines = ["*كتالوج المنتجات:*"]
        for p in products:
            lines.append(f"• {p['name']} — {p['price']} ج.م")
        await query.edit_message_text("\\n".join(lines), parse_mode="Markdown")
        return

    if data.startswith("add_cart:"):
        pid = data.split(":", 1)[1]
        CartService().add_item(uid, pid)
        await query.edit_message_text("✅ تمت الإضافة للسلة. استخدم /cart للعرض.")
        return

    if data in ("cart", "السلة") or data.endswith("السلة"):
        items = CartService().get_items(uid)
        if not items:
            await query.edit_message_text("السلة فارغة.")
        else:
            total = sum(i["price"] * i["qty"] for i in items)
            await query.edit_message_text(f"في السلة {len(items)} عنصر — الإجمالي {total} ج.م\\n/cart للتفاصيل")
        return

    if data == "checkout":
        order_id = OrderService().create_from_cart(uid)
        CartService().clear(uid)
        await query.edit_message_text(f"✅ تم إنشاء الطلب #{order_id}\\nسنتواصل معك قريباً.")
        return

    if data == "clear_cart":
        CartService().clear(uid)
        await query.edit_message_text("تم تفريغ السلة.")
        return

    if data.startswith("admin_"):
        await query.edit_message_text(f"قسم الإدارة: {data}\\n(قم بربط قاعدة البيانات للتشغيل الكامل)")
        return

    if data in ("main_menu", "start_action"):
        await query.edit_message_text("استخدم /start لعرض القائمة الرئيسية.")
        return

    await query.edit_message_text(f"تم اختيار: {data}")
'''


def render_message_handler(spec: FormalBotSpec) -> str:
    return '''"""Fallback text message handler (checkout data collection, etc.)."""
from __future__ import annotations
import logging
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger(__name__)

async def message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None or not message.text:
        return
    text = message.text.strip()
    state = (context.user_data or {}).get("state")
    if state == "awaiting_address":
        context.user_data["address"] = text
        context.user_data["state"] = None
        await message.reply_text("تم حفظ العنوان. أكمل من /cart")
        return
    logger.info("Message (%d chars)", len(text))
    await message.reply_text("استخدم الأزرار أو الأوامر: /start /products /cart /orders")
'''


def render_models(spec: FormalBotSpec) -> str:
    return '''"""Domain models."""
from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field

class StrictModel(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

class UserState(str, Enum):
    IDLE = "idle"
    WAITING_INPUT = "waiting_input"
    CHECKOUT = "checkout"

class Product(StrictModel):
    id: str
    name: str
    price: int
    description: str = ""

class CartItem(StrictModel):
    product_id: str
    name: str
    price: int
    qty: int = 1

class OrderStatus(str, Enum):
    NEW = "new"
    PAID = "paid"
    SHIPPED = "shipped"
    DONE = "done"
    CANCELLED = "cancelled"

class Order(StrictModel):
    id: str
    user_id: int
    items: list[CartItem]
    total: int
    status: OrderStatus = OrderStatus.NEW
'''


def render_catalog_service(spec: FormalBotSpec) -> str:
    return '''"""In-memory catalog (replace with DB later)."""
from __future__ import annotations

_PRODUCTS = [
    {"id": "1", "name": "منتج أ", "price": 100, "description": "وصف المنتج أ"},
    {"id": "2", "name": "منتج ب", "price": 250, "description": "وصف المنتج ب"},
    {"id": "3", "name": "منتج ج", "price": 75, "description": "وصف المنتج ج"},
]

class CatalogService:
    def list_products(self) -> list[dict]:
        return list(_PRODUCTS)

    def get(self, product_id: str) -> dict | None:
        for p in _PRODUCTS:
            if p["id"] == product_id:
                return p
        return None
'''


def render_cart_service(spec: FormalBotSpec) -> str:
    return '''"""In-memory cart service."""
from __future__ import annotations
from app.services.catalog import CatalogService

_CARTS: dict[int, list[dict]] = {}

class CartService:
    def get_items(self, user_id: int) -> list[dict]:
        return list(_CARTS.get(user_id, []))

    def add_item(self, user_id: int, product_id: str, qty: int = 1) -> None:
        product = CatalogService().get(product_id)
        if not product:
            return
        cart = _CARTS.setdefault(user_id, [])
        for item in cart:
            if item["id"] == product_id:
                item["qty"] += qty
                return
        cart.append({"id": product_id, "name": product["name"], "price": product["price"], "qty": qty})

    def clear(self, user_id: int) -> None:
        _CARTS[user_id] = []
'''


def render_orders_service(spec: FormalBotSpec) -> str:
    return '''"""In-memory orders service."""
from __future__ import annotations
import itertools
from app.services.cart import CartService

_ORDERS: list[dict] = []
_ID = itertools.count(1001)

class OrderService:
    def create_from_cart(self, user_id: int) -> int:
        items = CartService().get_items(user_id)
        total = sum(i["price"] * i["qty"] for i in items)
        oid = next(_ID)
        _ORDERS.append({
            "id": oid,
            "user_id": user_id,
            "items": items,
            "total": total,
            "status": "new",
        })
        return oid

    def list_user_orders(self, user_id: int) -> list[dict]:
        return [o for o in _ORDERS if o["user_id"] == user_id]

    def list_all(self) -> list[dict]:
        return list(_ORDERS)
'''


def render_readme(spec: FormalBotSpec) -> str:
    cmds = ", ".join(f"/{c.command}" for c in spec.ui.commands) or "/start"
    btns = ", ".join(b.text for b in spec.ui.main_buttons) or "—"
    return f"""# {spec.bot_name}

Generated by **Formal Bot Engine**.

## Type
`{spec.bot_type.value}`

## Commands
{cmds}

## Buttons
{btns}

## Flags
- Database: `{spec.database.value}`
- Payments: `{spec.requires_payments}`
- Admin: `{spec.requires_admin_panel}`
- Queue: `{spec.requires_async_queue}`

## Run
```bash
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env   # set TELEGRAM_BOT_TOKEN and ADMIN_USER_IDS
python -m app.main
```
"""


def render_pyproject(spec: FormalBotSpec) -> str:
    name = re.sub(r"[^a-z0-9]+", "-", spec.bot_name.lower()).strip("-") or "telegram-bot"
    return f'''[project]
name = "{name}"
version = "{spec.version}"
description = "{spec.bot_name}"
requires-python = ">=3.11"
[tool.ruff]
line-length = 100
target-version = "py311"
'''
