"""
General-purpose high-quality templates for ANY Telegram bot.
No domain lock-in. Clean, typed, production-ready.
"""

from __future__ import annotations

import re

from ..schemas.formal_spec import FormalBotSpec


def render_requirements(spec: FormalBotSpec) -> str:
    deps = [
        "python-telegram-bot>=21.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0",
        "pydantic-settings>=2.0",
    ]
    if spec.database.value == "postgres":
        deps.extend(["asyncpg>=0.29.0", "sqlalchemy[asyncio]>=2.0"])
    elif spec.database.value == "sqlite":
        deps.append("aiosqlite>=0.20.0")
    if spec.requires_async_queue:
        deps.extend(["arq>=0.26.0", "redis>=5.0"])
    if spec.requires_payments:
        deps.append("stripe>=8.0")
    return "\n".join(sorted(set(deps))) + "\n"


def render_env_example(spec: FormalBotSpec) -> str:
    lines = [
        "TELEGRAM_BOT_TOKEN=your-bot-token-here",
        "ALLOWED_USER_IDS=",
        f"BOT_NAME={spec.bot_name}",
        "LOG_LEVEL=INFO",
        "",
    ]
    if spec.database.value == "postgres":
        lines += ["DATABASE_URL=postgresql+asyncpg://user:pass@localhost:5432/botdb", ""]
    if spec.requires_async_queue:
        lines += ["REDIS_URL=redis://localhost:6379/0", ""]
    if spec.requires_payments:
        lines += ["STRIPE_SECRET_KEY=", "STRIPE_WEBHOOK_SECRET=", ""]
    return "\n".join(lines)


def render_config(spec: FormalBotSpec) -> str:
    return f'''"""
Application configuration – strict & typed.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Set

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    telegram_bot_token: str = Field(..., min_length=30)
    allowed_user_ids: str = ""
    bot_name: str = "{spec.bot_name}"
    log_level: str = "INFO"
    database_url: str | None = None
    redis_url: str | None = None

    @field_validator("allowed_user_ids", mode="before")
    @classmethod
    def _parse(cls, v: object) -> str:
        return "" if v is None else str(v)

    @property
    def allowed_ids(self) -> Set[int]:
        if not self.allowed_user_ids.strip():
            return set()
        return {{int(x.strip()) for x in self.allowed_user_ids.split(",") if x.strip().isdigit()}}


@lru_cache
def get_settings() -> Settings:
    return Settings()
'''


def render_main(spec: FormalBotSpec) -> str:
    safe = re.sub(r"[^a-z0-9_]", "_", spec.bot_name.lower())
    return f'''"""
{spec.bot_name} – Telegram Bot
Generated by Formal Bot Engine (general purpose).
"""

from __future__ import annotations

import logging
import sys

from telegram import Update
from telegram.ext import Application, CallbackQueryHandler, CommandHandler, MessageHandler, filters

from app.config import get_settings
from app.handlers.callbacks import callback_handler
from app.handlers.messages import message_handler
from app.handlers.start import start_handler

logging.basicConfig(
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    level=logging.INFO,
    stream=sys.stdout,
)
logger = logging.getLogger("{safe}")


def build_application() -> Application:
    settings = get_settings()
    app = Application.builder().token(settings.telegram_bot_token).build()

    app.add_handler(CommandHandler("start", start_handler))
    app.add_handler(CommandHandler("help", start_handler))
    app.add_handler(CallbackQueryHandler(callback_handler))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, message_handler))

    return app


def main() -> None:
    logger.info("Starting %s ...", "{spec.bot_name}")
    application = build_application()
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
'''


def render_start_handler(spec: FormalBotSpec) -> str:
    if spec.ui.main_buttons:
        rows = []
        for b in spec.ui.main_buttons[:4]:
            text = b.text.replace('"', '\\"')
            cb = b.callback_data.replace('"', '\\"')
            rows.append(f'        [InlineKeyboardButton("{text}", callback_data="{cb}")]')
        buttons_code = ",\n".join(rows)
    else:
        buttons_code = '        [InlineKeyboardButton("ابدأ", callback_data="start_action")]'

    welcome = (spec.ui.welcome_message or f"مرحبًا بك في {spec.bot_name}").replace('"', '\\"')
    return f'''"""
/start and /help handlers.
"""

from __future__ import annotations

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.constants import ParseMode
from telegram.ext import ContextTypes


async def start_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None:
        return

    keyboard = [
{buttons_code}
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    text = """{welcome}"""

    await message.reply_text(text, parse_mode=ParseMode.MARKDOWN, reply_markup=reply_markup)
'''


def render_message_handler(spec: FormalBotSpec) -> str:
    return '''"""
General text message handler.
"""

from __future__ import annotations

import logging

from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger(__name__)


async def message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    if message is None or not message.text:
        return

    text = message.text.strip()
    logger.info("Received message (%d chars)", len(text))

    await message.reply_text(
        "تم استلام رسالتك. سيتم معالجة الطلب حسب إعدادات البوت."
    )
'''


def render_callback_handler(spec: FormalBotSpec) -> str:
    return '''"""
Callback query handler for inline buttons.
"""

from __future__ import annotations

from telegram import Update
from telegram.ext import ContextTypes


async def callback_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    if query is None:
        return

    await query.answer()
    data = query.data or ""

    if data in ("start_action", "main"):
        await query.edit_message_text("أرسل طلبك أو اختر من القائمة.")
    else:
        await query.edit_message_text(f"تم اختيار: {data}")
'''


def render_models(spec: FormalBotSpec) -> str:
    return '''"""
Domain models – general purpose.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StrictModel(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class UserState(str, Enum):
    IDLE = "idle"
    WAITING_INPUT = "waiting_input"
    PROCESSING = "processing"


class BotContext(StrictModel):
    user_id: int
    state: UserState = UserState.IDLE
    data: dict[str, Any] = Field(default_factory=dict)
'''


def render_readme(spec: FormalBotSpec) -> str:
    feats = ", ".join(f.name for f in spec.features[:8]) or "—"
    caps = ", ".join(spec.capabilities) or "—"
    return f"""# {spec.bot_name}

Generated by **Formal Bot Engine** – general-purpose deterministic generator.

## Description

{spec.description[:400]}

## Spec Summary

| Field | Value |
|-------|-------|
| Type | `{spec.bot_type.value}` |
| Capabilities | {caps} |
| Features | {feats} |
| Languages | {", ".join(l.value for l in spec.languages)} |
| Database | `{spec.database.value}` |
| Async Queue | `{spec.requires_async_queue}` |
| Admin Panel | `{spec.requires_admin_panel}` |
| Payments | `{spec.requires_payments}` |

## Run

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
# set TELEGRAM_BOT_TOKEN
python -m app.main
```

## Structure

```
app/
├── main.py
├── config.py
├── models.py
├── handlers/
│   ├── start.py
│   ├── messages.py
│   └── callbacks.py
└── services/
```

Clean • Typed • Extensible • Deterministic
"""


def render_pyproject(spec: FormalBotSpec) -> str:
    name = re.sub(r"[^a-z0-9]+", "-", spec.bot_name.lower()).strip("-") or "telegram-bot"
    return f'''[project]
name = "{name}"
version = "{spec.version}"
description = "{spec.bot_name}"
requires-python = ">=3.11"

[tool.ruff]
line-length = 100
target-version = "py311"
'''
