"""GitHub REST API integration (Issues, PRs, comments) + App auth."""
from .client import (
    GitHubClient,
    client_for_user,
    client_for_repo,
    resolve_access_token,
    get_authenticated_user,
    list_user_repos,
    add_issue_comment,
    create_issue,
    get_pull,
    list_issue_comments,
    list_pull_files,
    create_pull_review,
    list_repo_issues,
)
from .app_auth import (
    github_app_configured,
    get_installation_token,
    build_app_jwt,
    clear_installation_token_cache,
    create_installation_access_token,
    get_installation,
    install_url,
    list_installation_repos,
    get_repo_installation,
    get_token_for_repo,
)

__all__ = [
    "GitHubClient",
    "client_for_user",
    "client_for_repo",
    "resolve_access_token",
    "get_authenticated_user",
    "list_user_repos",
    "add_issue_comment",
    "create_issue",
    "get_pull",
    "list_issue_comments",
    "list_pull_files",
    "create_pull_review",
    "list_repo_issues",
    "github_app_configured",
    "get_installation_token",
    "build_app_jwt",
    "clear_installation_token_cache",
    "create_installation_access_token",
    "get_installation",
    "install_url",
    "list_installation_repos",
    "get_repo_installation",
    "get_token_for_repo",
]
