"""Emit service modules (moderation, tasks, notes, tickets, security, extras, content, welcome)."""
from __future__ import annotations

from .schema import BotSpec


def _emit_moderation() -> str:
    """Advanced group moderation: ranks, warns, protection, anti-raid, audit log."""
    return (
        "\"\"\"Moderation service — ranks, warns, protection, anti-raid, per-chat settings.\"\"\"\n"
        "from __future__ import annotations\n"
        "\n"
        "import re\n"
        "import time\n"
        "from collections import defaultdict\n"
        "from telegram import ChatPermissions\n"
        "from telegram.ext import ContextTypes\n"
        "\n"
        "from app.db import connect, init_db\n"
        "\n"
        "_flood_bucket: dict[tuple[int, int], list[float]] = defaultdict(list)\n"
        "_join_bucket: dict[int, list[float]] = defaultdict(list)\n"
        "\n"
        "ROLE_ORDER = {\"member\": 0, \"moderator\": 1, \"admin\": 2, \"owner\": 3}\n"
        "\n"
        "\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS warns (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"count INTEGER NOT NULL DEFAULT 0, last_ts INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS admin_log (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"admin_id INTEGER NOT NULL, action TEXT NOT NULL, target_id INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"detail TEXT NOT NULL DEFAULT '', ts INTEGER NOT NULL)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS chat_settings (\"\n"
        "            \"chat_id INTEGER PRIMARY KEY, \"\n"
        "            \"max_warns INTEGER NOT NULL DEFAULT 3, \"\n"
        "            \"warn_ttl_hours INTEGER NOT NULL DEFAULT 168, \"\n"
        "            \"anti_link INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_spam INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_flood INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_raid INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"flood_limit INTEGER NOT NULL DEFAULT 6, \"\n"
        "            \"flood_window INTEGER NOT NULL DEFAULT 8, \"\n"
        "            \"raid_joins INTEGER NOT NULL DEFAULT 8, \"\n"
        "            \"raid_window INTEGER NOT NULL DEFAULT 20, \"\n"
        "            \"escalation TEXT NOT NULL DEFAULT 'warn,mute,kick,ban', \"\n"
        "            \"owner_id INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"leave_msg TEXT NOT NULL DEFAULT '', \"\n"
        "            \"leave_on INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"rules_on_join INTEGER NOT NULL DEFAULT 1)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS chat_roles (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"role TEXT NOT NULL DEFAULT 'member', \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS forbidden_words (\"\n"
        "            \"chat_id INTEGER NOT NULL, word TEXT NOT NULL, \"\n"
        "            \"PRIMARY KEY (chat_id, word))\"\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def log_action(chat_id: int, admin_id: int, action: str, target_id: int = 0, detail: str = \"\") -> None:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO admin_log (chat_id, admin_id, action, target_id, detail, ts) VALUES (?, ?, ?, ?, ?, ?)\",\n"
        "            (int(chat_id), int(admin_id), action, int(target_id), (detail or \"\")[:300], int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def list_log(chat_id: int, limit: int = 15) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT action, admin_id, target_id, detail, ts FROM admin_log \"\n"
        "            \"WHERE chat_id = ? ORDER BY id DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 40))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا أحداث في السجل\"\n"
        "    out = []\n"
        "    for r in rows:\n"
        "        ts = time.strftime(\"%Y-%m-%d %H:%M\", time.localtime(int(r[\"ts\"])))\n"
        "        out.append(f\"• [{ts}] {r['action']} by={r['admin_id']} target={r['target_id']} {r['detail']}\")\n"
        "    return \"\\n\".join(out)\n"
        "\n"
        "\n"
        "def get_settings(chat_id: int) -> dict:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\"SELECT * FROM chat_settings WHERE chat_id = ?\", (int(chat_id),)).fetchone()\n"
        "    if not row:\n"
        "        return {\n"
        "            \"max_warns\": 3, \"warn_ttl_hours\": 168,\n"
        "            \"anti_link\": 1, \"anti_spam\": 1, \"anti_flood\": 1, \"anti_raid\": 1,\n"
        "            \"flood_limit\": 6, \"flood_window\": 8, \"raid_joins\": 8, \"raid_window\": 20,\n"
        "            \"escalation\": \"warn,mute,kick,ban\", \"owner_id\": 0,\n"
        "            \"leave_msg\": \"\", \"leave_on\": 0, \"rules_on_join\": 1,\n"
        "        }\n"
        "    return dict(row)\n"
        "\n"
        "\n"
        "def _upsert_settings(chat_id: int, **fields) -> None:\n"
        "    ensure()\n"
        "    cur = get_settings(chat_id)\n"
        "    cur.update({k: v for k, v in fields.items() if v is not None})\n"
        "    vals = (\n"
        "        int(chat_id),\n"
        "        int(cur[\"max_warns\"]), int(cur[\"warn_ttl_hours\"]),\n"
        "        int(cur[\"anti_link\"]), int(cur[\"anti_spam\"]), int(cur[\"anti_flood\"]), int(cur[\"anti_raid\"]),\n"
        "        int(cur[\"flood_limit\"]), int(cur[\"flood_window\"]), int(cur[\"raid_joins\"]), int(cur[\"raid_window\"]),\n"
        "        str(cur.get(\"escalation\") or \"warn,mute,kick,ban\"),\n"
        "        int(cur.get(\"owner_id\") or 0),\n"
        "        str(cur.get(\"leave_msg\") or \"\")[:500],\n"
        "        int(cur.get(\"leave_on\") or 0),\n"
        "        int(cur.get(\"rules_on_join\") if cur.get(\"rules_on_join\") is not None else 1),\n"
        "    )\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO chat_settings (\"\n"
        "            \"chat_id, max_warns, warn_ttl_hours, anti_link, anti_spam, anti_flood, anti_raid, \"\n"
        "            \"flood_limit, flood_window, raid_joins, raid_window, escalation, owner_id, \"\n"
        "            \"leave_msg, leave_on, rules_on_join) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) \"\n"
        "            \"ON CONFLICT(chat_id) DO UPDATE SET \"\n"
        "            \"max_warns=excluded.max_warns, warn_ttl_hours=excluded.warn_ttl_hours, \"\n"
        "            \"anti_link=excluded.anti_link, anti_spam=excluded.anti_spam, \"\n"
        "            \"anti_flood=excluded.anti_flood, anti_raid=excluded.anti_raid, \"\n"
        "            \"flood_limit=excluded.flood_limit, flood_window=excluded.flood_window, \"\n"
        "            \"raid_joins=excluded.raid_joins, raid_window=excluded.raid_window, \"\n"
        "            \"escalation=excluded.escalation, owner_id=excluded.owner_id, \"\n"
        "            \"leave_msg=excluded.leave_msg, leave_on=excluded.leave_on, \"\n"
        "            \"rules_on_join=excluded.rules_on_join\",\n"
        "            vals,\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def set_max_warns(chat_id: int, n: int) -> str:\n"
        "    n = max(1, min(int(n), 20))\n"
        "    _upsert_settings(chat_id, max_warns=n)\n"
        "    return f\"حد التحذيرات أصبح {n}\"\n"
        "\n"
        "\n"
        "def set_protection(\n"
        "    chat_id: int,\n"
        "    anti_link: int | None = None,\n"
        "    anti_spam: int | None = None,\n"
        "    anti_flood: int | None = None,\n"
        "    anti_raid: int | None = None,\n"
        ") -> str:\n"
        "    fields = {}\n"
        "    if anti_link is not None:\n"
        "        fields[\"anti_link\"] = 1 if anti_link else 0\n"
        "    if anti_spam is not None:\n"
        "        fields[\"anti_spam\"] = 1 if anti_spam else 0\n"
        "    if anti_flood is not None:\n"
        "        fields[\"anti_flood\"] = 1 if anti_flood else 0\n"
        "    if anti_raid is not None:\n"
        "        fields[\"anti_raid\"] = 1 if anti_raid else 0\n"
        "    if fields:\n"
        "        _upsert_settings(chat_id, **fields)\n"
        "    s = get_settings(chat_id)\n"
        "    return (\n"
        "        f\"الحماية: روابط={'تشغيل' if s['anti_link'] else 'إيقاف'} | \"\n"
        "        f\"سبام={'تشغيل' if s['anti_spam'] else 'إيقاف'} | \"\n"
        "        f\"فيض={'تشغيل' if s['anti_flood'] else 'إيقاف'} | \"\n"
        "        f\"غارة={'تشغيل' if s['anti_raid'] else 'إيقاف'}\"\n"
        "    )\n"
        "\n"
        "\n"
        "def set_owner(chat_id: int, user_id: int) -> str:\n"
        "    _upsert_settings(chat_id, owner_id=int(user_id))\n"
        "    set_role(chat_id, int(user_id), \"owner\")\n"
        "    return f\"تم تعيين Owner: {user_id}\"\n"
        "\n"
        "\n"
        "def get_role(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    s = get_settings(chat_id)\n"
        "    if int(s.get(\"owner_id\") or 0) == int(user_id):\n"
        "        return \"owner\"\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT role FROM chat_roles WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    return str(row[\"role\"]) if row else \"member\"\n"
        "\n"
        "\n"
        "def set_role(chat_id: int, user_id: int, role: str) -> str:\n"
        "    role = (role or \"member\").lower().strip()\n"
        "    if role not in ROLE_ORDER:\n"
        "        role = \"member\"\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO chat_roles (chat_id, user_id, role) VALUES (?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET role = excluded.role\",\n"
        "            (int(chat_id), int(user_id), role),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"رتبة {user_id}: {role}\"\n"
        "\n"
        "\n"
        "def can_act(chat_id: int, actor_id: int, target_id: int, min_role: str = \"moderator\") -> tuple[bool, str]:\n"
        "    actor_role = get_role(chat_id, actor_id)\n"
        "    target_role = get_role(chat_id, target_id)\n"
        "    if target_role == \"owner\" and actor_role != \"owner\":\n"
        "        return False, \"لا يمكن المساس بالـ Owner\"\n"
        "    if ROLE_ORDER.get(actor_role, 0) < ROLE_ORDER.get(min_role, 1):\n"
        "        return False, f\"صلاحيتك ({actor_role}) أقل من المطلوب ({min_role})\"\n"
        "    if int(actor_id) != int(target_id) and ROLE_ORDER.get(actor_role, 0) <= ROLE_ORDER.get(target_role, 0):\n"
        "        if actor_role != \"owner\":\n"
        "            return False, \"لا يمكنك تنفيذ إجراء على رتبة مساوية أو أعلى\"\n"
        "    return True, \"ok\"\n"
        "\n"
        "\n"
        "def is_owner_protected(chat_id: int, user_id: int) -> bool:\n"
        "    return get_role(chat_id, user_id) == \"owner\"\n"
        "\n"
        "\n"
        "def list_forbidden(chat_id: int) -> list[str]:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT word FROM forbidden_words WHERE chat_id = ? ORDER BY word\",\n"
        "            (int(chat_id),),\n"
        "        ).fetchall()\n"
        "    return [str(r[\"word\"]) for r in rows]\n"
        "\n"
        "\n"
        "def add_forbidden(chat_id: int, word: str) -> str:\n"
        "    w = (word or \"\").strip().lower()\n"
        "    if not w or len(w) > 64:\n"
        "        return \"كلمة غير صالحة\"\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT OR IGNORE INTO forbidden_words (chat_id, word) VALUES (?, ?)\",\n"
        "            (int(chat_id), w),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"أُضيفت للكلمات الممنوعة: {w}\"\n"
        "\n"
        "\n"
        "def remove_forbidden(chat_id: int, word: str) -> str:\n"
        "    w = (word or \"\").strip().lower()\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"DELETE FROM forbidden_words WHERE chat_id = ? AND word = ?\",\n"
        "            (int(chat_id), w),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"حُذفت من الممنوعة: {w}\"\n"
        "\n"
        "\n"
        "def has_forbidden(chat_id: int, text: str) -> str | None:\n"
        "    words = list_forbidden(chat_id)\n"
        "    if not words:\n"
        "        return None\n"
        "    t = (text or \"\").lower()\n"
        "    for w in words:\n"
        "        if w and w in t:\n"
        "            return w\n"
        "    return None\n"
        "\n"
        "\n"
        "def _purge_expired_warns(chat_id: int, user_id: int) -> None:\n"
        "    s = get_settings(chat_id)\n"
        "    ttl = max(1, int(s.get(\"warn_ttl_hours\") or 168)) * 3600\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count, last_ts FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        if not row:\n"
        "            return\n"
        "        if int(row[\"last_ts\"] or 0) and (time.time() - int(row[\"last_ts\"])) > ttl:\n"
        "            conn.execute(\n"
        "                \"UPDATE warns SET count = 0, last_ts = 0 WHERE chat_id = ? AND user_id = ?\",\n"
        "                (int(chat_id), int(user_id)),\n"
        "            )\n"
        "            conn.commit()\n"
        "\n"
        "\n"
        "def get_warns(chat_id: int, user_id: int) -> int:\n"
        "    _purge_expired_warns(chat_id, user_id)\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    return int(row[\"count\"]) if row else 0\n"
        "\n"
        "\n"
        "def clear_warnings(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"DELETE FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تم مسح تحذيرات {user_id}\"\n"
        "\n"
        "\n"
        "def unwarn_user(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    n = get_warns(chat_id, user_id)\n"
        "    if n <= 0:\n"
        "        return \"لا توجد تحذيرات\"\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"UPDATE warns SET count = ? WHERE chat_id = ? AND user_id = ?\",\n"
        "            (n - 1, int(chat_id), int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تحذيرات {user_id}: {n - 1}\"\n"
        "\n"
        "\n"
        "async def _apply_escalation(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, count: int) -> str:\n"
        "    s = get_settings(chat_id)\n"
        "    max_w = max(1, int(s.get(\"max_warns\") or 3))\n"
        "    steps = [x.strip() for x in str(s.get(\"escalation\") or \"warn,mute,kick,ban\").split(\",\") if x.strip()]\n"
        "    if count < max_w:\n"
        "        return f\"تحذير {count}/{max_w}\"\n"
        "    action = steps[min(len(steps) - 1, max(0, count - max_w))] if steps else \"mute\"\n"
        "    if action == \"mute\":\n"
        "        await mute_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: كتم (تحذيرات={count})\"\n"
        "    if action == \"kick\":\n"
        "        await kick_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: طرد (تحذيرات={count})\"\n"
        "    if action == \"ban\":\n"
        "        await ban_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: حظر (تحذيرات={count})\"\n"
        "    return f\"تحذير {count}/{max_w}\"\n"
        "\n"
        "\n"
        "async def warn_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, admin_id: int = 0) -> str:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return \"لا يمكن تحذير الـ Owner\"\n"
        "    if admin_id:\n"
        "        ok, reason = can_act(chat_id, admin_id, user_id, \"moderator\")\n"
        "        if not ok:\n"
        "            return reason\n"
        "    ensure()\n"
        "    _purge_expired_warns(chat_id, user_id)\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        n = (int(row[\"count\"]) if row else 0) + 1\n"
        "        conn.execute(\n"
        "            \"INSERT INTO warns (chat_id, user_id, count, last_ts) VALUES (?, ?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET count = excluded.count, last_ts = excluded.last_ts\",\n"
        "            (int(chat_id), int(user_id), n, int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "    if admin_id:\n"
        "        log_action(chat_id, admin_id, \"warn\", user_id, f\"count={n}\")\n"
        "    return await _apply_escalation(context, chat_id, user_id, n)\n"
        "\n"
        "\n"
        "async def ban_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.ban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def unban_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    await context.bot.unban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def mute_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, seconds: int = 3600) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    until = int(time.time()) + max(30, int(seconds))\n"
        "    perms = ChatPermissions(can_send_messages=False)\n"
        "    await context.bot.restrict_chat_member(chat_id=chat_id, user_id=user_id, permissions=perms, until_date=until)\n"
        "\n"
        "\n"
        "async def unmute_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    perms = ChatPermissions(\n"
        "        can_send_messages=True, can_send_media_messages=True,\n"
        "        can_send_other_messages=True, can_add_web_page_previews=True,\n"
        "    )\n"
        "    await context.bot.restrict_chat_member(chat_id=chat_id, user_id=user_id, permissions=perms)\n"
        "\n"
        "\n"
        "async def kick_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.ban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "    await context.bot.unban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def promote_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    await context.bot.promote_chat_member(\n"
        "        chat_id=chat_id, user_id=user_id,\n"
        "        can_delete_messages=True, can_restrict_members=True,\n"
        "        can_invite_users=True, can_pin_messages=True, can_promote_members=False,\n"
        "    )\n"
        "    set_role(chat_id, user_id, \"admin\")\n"
        "\n"
        "\n"
        "async def demote_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.promote_chat_member(\n"
        "        chat_id=chat_id, user_id=user_id,\n"
        "        can_delete_messages=False, can_restrict_members=False,\n"
        "        can_invite_users=False, can_pin_messages=False, can_promote_members=False,\n"
        "    )\n"
        "    set_role(chat_id, user_id, \"member\")\n"
        "\n"
        "\n"
        "async def pin_message(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.pin_chat_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "async def delete_message(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.delete_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "async def purge(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.delete_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "def slowmode_info() -> str:\n"
        "    return \"الوضع البطيء يُضبط من إعدادات تيليجرام للجروب أو عبر صلاحيات البوت إن توفرت.\"\n"
        "\n"
        "\n"
        "def user_info(user_id: int, chat_id: int = 0) -> str:\n"
        "    role = get_role(chat_id, user_id) if chat_id else \"member\"\n"
        "    warns = get_warns(chat_id, user_id) if chat_id else 0\n"
        "    return f\"المعرف: {user_id}\\nالرتبة: {role}\\nالتحذيرات: {warns}\"\n"
        "\n"
        "\n"
        "def looks_like_link(text: str) -> bool:\n"
        "    t = (text or \"\").lower()\n"
        "    return (\"http://\" in t) or (\"https://\" in t) or (\"t.me/\" in t) or (\"www.\" in t)\n"
        "\n"
        "\n"
        "def looks_like_spam(text: str) -> bool:\n"
        "    t = (text or \"\").strip()\n"
        "    if len(t) > 800:\n"
        "        return True\n"
        "    if t and len(set(t)) <= 2 and len(t) >= 12:\n"
        "        return True\n"
        "    if len(re.findall(r\"(.)\\1{6,}\", t)) >= 1:\n"
        "        return True\n"
        "    return False\n"
        "\n"
        "\n"
        "def record_message_flood(chat_id: int, user_id: int) -> bool:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"anti_flood\") or 0):\n"
        "        return False\n"
        "    now = time.time()\n"
        "    window = max(3, int(s.get(\"flood_window\") or 8))\n"
        "    limit = max(3, int(s.get(\"flood_limit\") or 6))\n"
        "    key = (int(chat_id), int(user_id))\n"
        "    bucket = [t for t in _flood_bucket[key] if now - t <= window]\n"
        "    bucket.append(now)\n"
        "    _flood_bucket[key] = bucket\n"
        "    return len(bucket) > limit\n"
        "\n"
        "\n"
        "def record_join(chat_id: int) -> bool:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"anti_raid\") or 0):\n"
        "        return False\n"
        "    now = time.time()\n"
        "    window = max(5, int(s.get(\"raid_window\") or 20))\n"
        "    limit = max(3, int(s.get(\"raid_joins\") or 8))\n"
        "    bucket = [t for t in _join_bucket[int(chat_id)] if now - t <= window]\n"
        "    bucket.append(now)\n"
        "    _join_bucket[int(chat_id)] = bucket\n"
        "    return len(bucket) > limit\n"
        "\n"
        "\n"
        "def set_leave_message(chat_id: int, text: str, enabled: int = 1) -> str:\n"
        "    _upsert_settings(chat_id, leave_msg=(text or \"\")[:500], leave_on=1 if enabled else 0)\n"
        "    return \"تم تحديث رسالة المغادرة\"\n"
        "\n"
        "\n"
        "def get_leave_message(chat_id: int) -> str:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"leave_on\") or 0):\n"
        "        return \"\"\n"
        "    return str(s.get(\"leave_msg\") or \"\")\n"
    )


def _emit_tasks() -> str:
    return '''"""Tasks service — sqlite-backed personal tasks."""
from __future__ import annotations

from app.db import connect, init_db


def ensure() -> None:
    init_db()


def add_task(user_id: int, title: str, description: str = "", priority: str = "medium") -> int:
    ensure()
    priority = priority if priority in {"high", "medium", "low"} else "medium"
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO tasks (user_id, title, description, priority, done) VALUES (?, ?, ?, ?, 0)",
            (user_id, title, description, priority),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_tasks(user_id: int, only_open: bool = True) -> list[dict]:
    ensure()
    q = "SELECT id, title, description, priority, done FROM tasks WHERE user_id = ?"
    if only_open:
        q += " AND done = 0"
    q += " ORDER BY id DESC"
    with connect() as conn:
        rows = conn.execute(q, (user_id,)).fetchall()
    return [dict(r) for r in rows]


def done_task(user_id: int, task_id: int) -> bool:
    ensure()
    with connect() as conn:
        cur = conn.execute(
            "UPDATE tasks SET done = 1 WHERE id = ? AND user_id = ?",
            (task_id, user_id),
        )
        conn.commit()
        return cur.rowcount > 0


def delete_task(user_id: int, task_id: int) -> bool:
    ensure()
    with connect() as conn:
        cur = conn.execute(
            "DELETE FROM tasks WHERE id = ? AND user_id = ?",
            (task_id, user_id),
        )
        conn.commit()
        return cur.rowcount > 0


def clear_tasks(user_id: int) -> int:
    ensure()
    with connect() as conn:
        cur = conn.execute("DELETE FROM tasks WHERE user_id = ? AND done = 1", (user_id,))
        conn.commit()
        return int(cur.rowcount)
'''



def _emit_notes() -> str:
    return '''"""Notes service — personal notes in sqlite."""
from __future__ import annotations

from app.db import connect, init_db


def ensure() -> None:
    init_db()


def add_note(user_id: int, body: str) -> int:
    ensure()
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO notes (user_id, body) VALUES (?, ?)",
            (user_id, body),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_notes(user_id: int) -> list[dict]:
    ensure()
    with connect() as conn:
        rows = conn.execute(
            "SELECT id, body FROM notes WHERE user_id = ? ORDER BY id DESC",
            (user_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def delete_note(user_id: int, note_id: int) -> bool:
    ensure()
    with connect() as conn:
        cur = conn.execute(
            "DELETE FROM notes WHERE id = ? AND user_id = ?",
            (note_id, user_id),
        )
        conn.commit()
        return cur.rowcount > 0
'''



def _emit_content(spec: BotSpec) -> str:
    rules = "التزم بالاحترام. ممنوع السبام والإعلانات." if (spec.bot.language or "ar").startswith("ar") else "Be respectful. No spam."
    about = spec.bot.description or spec.bot.name
    return (
        '"""Static content helpers."""\n'
        "from __future__ import annotations\n\n"
        f"RULES_TEXT = {rules!r}\n"
        f"ABOUT_TEXT = {about!r}\n\n"
        "def rules() -> str:\n"
        "    return RULES_TEXT\n\n"
        "def about() -> str:\n"
        "    return ABOUT_TEXT\n\n"
        "def faq() -> str:\n"
        "    return (\n"
        '        "الأسئلة الشائعة:\\n"\n'
        '        "- /start للبداية\\n"\n'
        '        "- /help للأوامر\\n"\n'
        '        "- للمساعدة تواصل مع المشرف"\n'
        "    )\n"
    )



def _emit_welcome() -> str:
    return (
        '"""Welcome service — per-chat auto-welcome for new members."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n"
        'DEFAULT_MESSAGE = "أهلاً {name} 👋 نورت المجموعة!"\n\n'
        "def ensure() -> None:\n"
        "    init_db()\n\n"
        "def set_message(chat_id: int, message: str) -> None:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        '            """\n'
        "            INSERT INTO welcome_settings (chat_id, enabled, message) VALUES (?, 1, ?)\n"
        "            ON CONFLICT(chat_id) DO UPDATE SET message = excluded.message, enabled = 1\n"
        '            """,\n'
        "            (chat_id, message),\n"
        "        )\n"
        "        conn.commit()\n\n"
        "def toggle(chat_id: int) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        '            "SELECT enabled FROM welcome_settings WHERE chat_id = ?", (chat_id,)\n'
        "        ).fetchone()\n"
        "        if row is None:\n"
        "            conn.execute(\n"
        '                "INSERT INTO welcome_settings (chat_id, enabled, message) VALUES (?, 1, ?)",\n'
        "                (chat_id, DEFAULT_MESSAGE),\n"
        "            )\n"
        "            conn.commit()\n"
        "            return True\n"
        "        new_val = 0 if int(row['enabled']) else 1\n"
        "        conn.execute(\n"
        '            "UPDATE welcome_settings SET enabled = ? WHERE chat_id = ?",\n'
        "            (new_val, chat_id),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return bool(new_val)\n\n"
        "def get_settings(chat_id: int) -> dict:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        '            "SELECT enabled, message FROM welcome_settings WHERE chat_id = ?",\n'
        "            (chat_id,),\n"
        "        ).fetchone()\n"
        "    if row is None:\n"
        '        return {"enabled": True, "message": DEFAULT_MESSAGE}\n'
        "    return {\n"
        "        'enabled': bool(int(row['enabled'])),\n"
        "        'message': row['message'] or DEFAULT_MESSAGE,\n"
        "    }\n\n"
        "def format_welcome(chat_id: int, name: str) -> str | None:\n"
        "    cfg = get_settings(chat_id)\n"
        "    if not cfg['enabled']:\n"
        "        return None\n"
        "    msg = cfg['message'] or DEFAULT_MESSAGE\n"
        "    return msg.replace('{name}', name).replace('{NAME}', name)\n"
    )


def _emit_tickets() -> str:
    return (
        '"""Support tickets service — open/close/list/reply with sqlite."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n"
        "def open_ticket(user_id: int, subject: str, chat_id: int = 0) -> int:\n"
        "    ensure()\n"
        '    subject = (subject or "").strip() or "بدون عنوان"\n'
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        '            "INSERT INTO tickets (user_id, chat_id, subject, status) VALUES (?, ?, ?, \'open\')",\n'
        "            (user_id, chat_id, subject[:200]),\n"
        "        )\n"
        "        tid = int(cur.lastrowid)\n"
        "        conn.execute(\n"
        '            "INSERT INTO ticket_messages (ticket_id, user_id, is_staff, body) VALUES (?, ?, 0, ?)",\n'
        "            (tid, user_id, subject),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return tid\n\n"
        "def close_ticket(ticket_id: int, user_id: int | None = None, staff: bool = False) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        row = conn.execute("SELECT user_id, status FROM tickets WHERE id = ?", (ticket_id,)).fetchone()\n'
        "        if row is None:\n"
        "            return False\n"
        "        if not staff and user_id is not None and int(row['user_id']) != int(user_id):\n"
        "            return False\n"
        "        if row['status'] == 'closed':\n"
        "            return True\n"
        '        conn.execute("UPDATE tickets SET status = \'closed\' WHERE id = ?", (ticket_id,))\n'
        "        conn.commit()\n"
        "        return True\n\n"
        "def list_tickets(user_id: int | None = None, only_open: bool = True, limit: int = 20) -> list[dict]:\n"
        "    ensure()\n"
        '    q = "SELECT id, user_id, subject, status, created_at FROM tickets WHERE 1=1"\n'
        "    params: list = []\n"
        "    if user_id is not None:\n"
        '        q += " AND user_id = ?"\n'
        "        params.append(user_id)\n"
        "    if only_open:\n"
        '        q += " AND status = \'open\'"\n'
        '    q += " ORDER BY id DESC LIMIT ?"\n'
        "    params.append(limit)\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(q, params).fetchall()\n"
        "    return [dict(r) for r in rows]\n\n"
        "def my_tickets(user_id: int) -> list[dict]:\n"
        "    return list_tickets(user_id=user_id, only_open=True)\n\n"
        "def reply_ticket(ticket_id: int, user_id: int, body: str, staff: bool = False) -> bool:\n"
        "    ensure()\n"
        '    body = (body or "").strip()\n'
        "    if not body:\n"
        "        return False\n"
        "    with connect() as conn:\n"
        '        row = conn.execute("SELECT id, status FROM tickets WHERE id = ?", (ticket_id,)).fetchone()\n'
        "        if row is None or row['status'] == 'closed':\n"
        "            return False\n"
        "        conn.execute(\n"
        '            "INSERT INTO ticket_messages (ticket_id, user_id, is_staff, body) VALUES (?, ?, ?, ?)",\n'
        "            (ticket_id, user_id, 1 if staff else 0, body),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return True\n\n"
        "def ticket_status(ticket_id: int) -> dict | None:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        '            "SELECT id, user_id, subject, status, created_at FROM tickets WHERE id = ?",\n'
        "            (ticket_id,),\n"
        "        ).fetchone()\n"
        "        if row is None:\n"
        "            return None\n"
        "        msgs = conn.execute(\n"
        '            "SELECT user_id, is_staff, body, created_at FROM ticket_messages WHERE ticket_id = ? ORDER BY id ASC LIMIT 10",\n'
        "            (ticket_id,),\n"
        "        ).fetchall()\n"
        "    data = dict(row)\n"
        "    data['messages'] = [dict(m) for m in msgs]\n"
        "    return data\n"
    )



def _emit_security() -> str:
    return (
        '"""Defensive security ops — reports, awareness, and passive domain checks.\n'
        "\n"
        "No offensive / exploit tooling. Network helpers use stdlib only.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "import re\n"
        "import socket\n"
        "import ssl\n"
        "from urllib.parse import urlparse\n"
        "from urllib.request import Request, urlopen\n\n"
        "from app.db import connect, init_db\n\n"
        "CHECKLIST = (\n"
        '    "1) لا تشارك كلمات المرور أو رموز التحقق\\n"\n'
        '    "2) راجع الروابط قبل الفتح\\n"\n'
        '    "3) فعّل التحقق بخطوتين\\n"\n'
        '    "4) بلّغ فورًا عن أي رسالة مشبوهة\\n"\n'
        '    "5) حدّث التطبيقات باستمرار"\n'
        ")\n\n"
        "TIPS = (\n"
        '    "• استخدم كلمات مرور فريدة لكل خدمة\\n"\n'
        '    "• فعّل 2FA / مفاتيح المرور\\n"\n'
        '    "• لا تفتح مرفقات غير متوقعة\\n"\n'
        '    "• راجع صلاحيات التطبيقات دوريًا"\n'
        ")\n\n"
        "PASSWORD_TIPS = (\n"
        '    "• 12+ حرف مع تنوع (أحرف/أرقام/رموز)\\n"\n'
        '    "• لا تعِد استخدام نفس كلمة المرور\\n"\n'
        '    "• مدير كلمات مرور موثوق أفضل من الذاكرة\\n"\n'
        '    "• غيّر فوريًا بعد أي تسريب معروف"\n'
        ")\n\n"
        "_HOST_RE = re.compile(r\"^[a-zA-Z0-9](?:[a-zA-Z0-9\\-\\.]{0,251}[a-zA-Z0-9])?$\")\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n"
        "def _clean_host(raw: str) -> str:\n"
        "    t = (raw or '').strip().lower()\n"
        "    if '://' in t:\n"
        "        t = urlparse(t).hostname or t\n"
        "    t = t.split('/')[0].split('?')[0].strip().strip('.')\n"
        "    if t.startswith('www.'):\n"
        "        t = t[4:]\n"
        "    if not t or not _HOST_RE.match(t) or len(t) > 253:\n"
        "        return ''\n"
        "    return t\n\n"
        "def report(user_id: int, kind: str, body: str) -> int:\n"
        "    ensure()\n"
        '    kind = (kind or "incident").strip()[:40]\n'
        '    body = (body or "").strip() or "—"\n'
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        '            "INSERT INTO security_reports (user_id, kind, body, status) VALUES (?, ?, ?, \'open\')",\n'
        "            (user_id, kind, body[:2000]),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return int(cur.lastrowid)\n\n"
        "def list_reports(only_open: bool = True, limit: int = 20) -> list[dict]:\n"
        "    ensure()\n"
        '    q = "SELECT id, user_id, kind, body, status, created_at FROM security_reports"\n'
        "    if only_open:\n"
        "        q += \" WHERE status = 'open'\"\n"
        "    q += \" ORDER BY id DESC LIMIT ?\"\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(q, (limit,)).fetchall()\n"
        "    return [dict(r) for r in rows]\n\n"
        "def close_report(report_id: int) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        cur = conn.execute("UPDATE security_reports SET status = \'closed\' WHERE id = ?", (report_id,))\n'
        "        conn.commit()\n"
        "        return cur.rowcount > 0\n\n"
        "def checklist() -> str:\n"
        "    return CHECKLIST\n\n"
        "def tips() -> str:\n"
        "    return TIPS\n\n"
        "def password_tips() -> str:\n"
        "    return PASSWORD_TIPS\n\n"
        "def dns_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /dns example.com'\n"
        "    lines = [f'DNS overview — {h}']\n"
        "    try:\n"
        "        infos = socket.getaddrinfo(h, None)\n"
        "        seen: set[str] = set()\n"
        "        for info in infos:\n"
        "            ip = info[4][0]\n"
        "            if ip in seen:\n"
        "                continue\n"
        "            seen.add(ip)\n"
        "            fam = 'AAAA' if ':' in ip else 'A'\n"
        "            lines.append(f'  {fam}: {ip}')\n"
        "            if len(seen) >= 8:\n"
        "                break\n"
        "        if not seen:\n"
        "            lines.append('  (no A/AAAA resolved)')\n"
        "    except socket.gaierror as exc:\n"
        "        lines.append(f'  resolve error: {exc}')\n"
        "    except Exception as exc:\n"
        "        lines.append(f'  error: {exc}')\n"
        "    lines.append('Note: passive lookup only (stdlib).')\n"
        "    return '\\n'.join(lines)\n\n"
        "def mx_check(host: str) -> str:\n"
        "    # Stdlib cannot query MX RRset without dnspython; give honest guidance + A lookup.\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /mx example.com'\n"
        "    base = dns_check(h)\n"
        "    return (\n"
        "        base + '\\n\\nMX tip: use dig/nslookup for MX/SPF/DMARC records. '\n"
        "        'This bot does passive A/AAAA only (no external DNS libs).'\n"
        "    )\n\n"
        "def tls_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /tls example.com'\n"
        "    try:\n"
        "        ctx = ssl.create_default_context()\n"
        "        with socket.create_connection((h, 443), timeout=8) as sock:\n"
        "            with ctx.wrap_socket(sock, server_hostname=h) as ssock:\n"
        "                cert = ssock.getpeercert()\n"
        "                ver = ssock.version()\n"
        "        subject = dict(x[0] for x in (cert or {}).get('subject', ()) )\n"
        "        issuer = dict(x[0] for x in (cert or {}).get('issuer', ()) )\n"
        "        not_after = (cert or {}).get('notAfter', '?')\n"
        "        cn = subject.get('commonName') or subject.get('organizationName') or '?'\n"
        "        iss = issuer.get('commonName') or issuer.get('organizationName') or '?'\n"
        "        return (\n"
        "            f'TLS overview — {h}\\n'\n"
        "            f'  protocol: {ver}\\n'\n"
        "            f'  subject CN: {cn}\\n'\n"
        "            f'  issuer: {iss}\\n'\n"
        "            f'  notAfter: {not_after}\\n'\n"
        "            'Passive certificate read only.'\n"
        "        )\n"
        "    except Exception as exc:\n"
        "        return f'TLS check failed for {h}: {exc}'\n\n"
        "def http_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /httpstatus example.com'\n"
        "    url = f'https://{h}/'\n"
        "    try:\n"
        "        req = Request(url, method='GET', headers={'User-Agent': 'SecBot/1.0'})\n"
        "        with urlopen(req, timeout=8) as resp:  # noqa: S310 — host validated\n"
        "            code = getattr(resp, 'status', None) or resp.getcode()\n"
        "            return f'HTTP {code} — {url}'\n"
        "    except Exception as exc:\n"
        "        return f'HTTP probe failed for {h}: {exc}'\n\n"
        "def headers_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /headers example.com'\n"
        "    url = f'https://{h}/'\n"
        "    interesting = (\n"
        "        'strict-transport-security', 'content-security-policy',\n"
        "        'x-frame-options', 'x-content-type-options', 'referrer-policy',\n"
        "        'permissions-policy', 'server',\n"
        "    )\n"
        "    try:\n"
        "        req = Request(url, method='GET', headers={'User-Agent': 'SecBot/1.0'})\n"
        "        with urlopen(req, timeout=8) as resp:  # noqa: S310\n"
        "            hdrs = {k.lower(): v for k, v in resp.headers.items()}\n"
        "        lines = [f'Security headers — {h}']\n"
        "        for key in interesting:\n"
        "            val = hdrs.get(key)\n"
        "            lines.append(f'  {key}: {val if val else \"(missing)\"}')\n"
        "        return '\\n'.join(lines)\n"
        "    except Exception as exc:\n"
        "        return f'Headers probe failed for {h}: {exc}'\n\n"
        "def domain_overview(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /domainscan example.com'\n"
        "    parts = [\n"
        "        dns_check(h),\n"
        "        '',\n"
        "        tls_check(h),\n"
        "        '',\n"
        "        http_check(h),\n"
        "        '',\n"
        "        headers_check(h),\n"
        "    ]\n"
        "    return '\\n'.join(parts)\n"
    )



def _emit_extras() -> str:
    """Shared lightweight services: shop/booking/crm/reminders/community/edu/hr/utils/gate."""
    return (
        '"""Market extras — lightweight product modules (deterministic)."""\n'
        "from __future__ import annotations\n\n"
        "import random\n"
        "from datetime import datetime, timezone\n"
        "from app.db import connect, init_db\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n"
        "def _add(user_id: int, kind: str, body: str, status: str = 'open') -> int:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        '            "INSERT INTO extras_kv (user_id, kind, body, status) VALUES (?, ?, ?, ?)",\n'
        "            (user_id, kind, body[:2000], status),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return int(cur.lastrowid)\n\n"
        "def _list(kind: str, user_id: int | None = None, only_open: bool = False, limit: int = 30) -> list[dict]:\n"
        "    ensure()\n"
        '    q = "SELECT id, user_id, kind, body, status, created_at FROM extras_kv WHERE kind = ?"\n'
        "    params: list = [kind]\n"
        "    if user_id is not None:\n"
        '        q += " AND user_id = ?"\n'
        "        params.append(user_id)\n"
        "    if only_open:\n"
        '        q += " AND status = \'open\'"\n'
        '    q += " ORDER BY id DESC LIMIT ?"\n'
        "    params.append(limit)\n"
        "    with connect() as conn:\n"
        "        return [dict(r) for r in conn.execute(q, params).fetchall()]\n\n"
        "def _close(item_id: int, kind: str | None = None) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        if kind:\n"
        '            cur = conn.execute("UPDATE extras_kv SET status = \'closed\' WHERE id = ? AND kind = ?", (item_id, kind))\n'
        "        else:\n"
        '            cur = conn.execute("UPDATE extras_kv SET status = \'closed\' WHERE id = ?", (item_id,))\n'
        "        conn.commit()\n"
        "        return cur.rowcount > 0\n\n"
        "# shop\n"
        "def catalog() -> str:\n"
        "    items = _list('product')\n"
        "    if not items:\n"
        "        return 'لا منتجات بعد'\n"
        "    return '\\n'.join(f\"#{i['id']} {i['body']}\" for i in items)\n\n"
        "def add_item(admin_id: int, title: str) -> int:\n"
        "    return _add(admin_id, 'product', title, 'open')\n\n"
        "def place_order(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'order', text)\n\n"
        "def list_orders() -> list[dict]:\n"
        "    return _list('order', only_open=True)\n\n"
        "# booking\n"
        "def book_slot(user_id: int, slot: str) -> int:\n"
        "    return _add(user_id, 'booking', slot)\n\n"
        "def list_bookings(user_id: int) -> list[dict]:\n"
        "    return _list('booking', user_id=user_id, only_open=True)\n\n"
        "def cancel_booking(user_id: int, item_id: int) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        cur = conn.execute("UPDATE extras_kv SET status = \'closed\' WHERE id = ? AND user_id = ? AND kind = \'booking\'", (item_id, user_id))\n'
        "        conn.commit()\n"
        "        return cur.rowcount > 0\n\n"
        "def admin_list_bookings() -> list[dict]:\n"
        "    return _list('booking', only_open=True)\n\n"
        "# crm\n"
        "def lead_capture(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'lead', text)\n\n"
        "def lead_list() -> list[dict]:\n"
        "    return _list('lead', only_open=True)\n\n"
        "# reminders\n"
        "def set_reminder(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'reminder', text)\n\n"
        "def list_reminders(user_id: int) -> list[dict]:\n"
        "    return _list('reminder', user_id=user_id, only_open=True)\n\n"
        "def clear_reminders(user_id: int) -> int:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        cur = conn.execute("UPDATE extras_kv SET status = \'closed\' WHERE user_id = ? AND kind = \'reminder\' AND status = \'open\'", (user_id,))\n'
        "        conn.commit()\n"
        "        return int(cur.rowcount)\n\n"
        "# community\n"
        "def feedback(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'feedback', text)\n\n"
        "def suggest(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'suggest', text)\n\n"
        "def report_user(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'user_report', text)\n\n"
        "def poll_create(admin_id: int, text: str) -> int:\n"
        "    return _add(admin_id, 'poll', text)\n\n"
        "# edu / hr\n"
        "def course_list() -> str:\n"
        "    items = _list('course')\n"
        "    return '\\n'.join(f\"#{i['id']} {i['body']}\" for i in items) if items else 'لا دورات'\n\n"
        "def enroll(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'enroll', text)\n\n"
        "def quiz_start() -> str:\n"
        "    return 'اختبار سريع: ما أقوى ممارسة أمنية؟ أ) مشاركة كلمة المرور ب) 2FA — اكتب إجابتك كرسالة'\n\n"
        "def leave_request(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'leave', text)\n\n"
        "def leave_list() -> list[dict]:\n"
        "    return _list('leave', only_open=True)\n\n"
        "def checkin(user_id: int) -> int:\n"
        "    return _add(user_id, 'checkin', datetime.now(timezone.utc).isoformat())\n\n"
        "# gate / utils\n"
        "def verify_start() -> str:\n"
        "    return 'للتحقق أرسل: أنا لست روبوت'\n\n"
        "def verify_ok(text: str) -> bool:\n"
        "    return 'لست روبوت' in (text or '') or 'not a robot' in (text or '').lower()\n\n"
        "def force_sub_info() -> str:\n"
        "    return 'الاشتراك الإجباري: أضف قناتك هنا من الإعدادات لاحقًا. هذه نسخة معلوماتية.'\n\n"
        "def calc(expr: str) -> str:\n"
        "    \"\"\"Safe arithmetic — no eval. Supports + - * / and parentheses.\"\"\"\n"
        "    import ast as _ast\n"
        "    import operator as _op\n"
        "    allowed_chars = set('0123456789+-*/(). %')\n"
        "    e = ''.join(ch for ch in (expr or '') if ch in allowed_chars).replace('%', '/100')\n"
        "    if not e:\n"
        "        return 'تعبير غير صالح'\n"
        "    ops = {\n"
        "        _ast.Add: _op.add, _ast.Sub: _op.sub, _ast.Mult: _op.mul,\n"
        "        _ast.Div: _op.truediv, _ast.USub: _op.neg, _ast.UAdd: _op.pos,\n"
        "    }\n"
        "    def _eval(node):\n"
        "        if isinstance(node, _ast.Expression):\n"
        "            return _eval(node.body)\n"
        "        if isinstance(node, _ast.Constant) and isinstance(node.value, (int, float)):\n"
        "            return node.value\n"
        "        if isinstance(node, _ast.Num):  # py<3.8\n"
        "            return node.n\n"
        "        if isinstance(node, _ast.BinOp) and type(node.op) in ops:\n"
        "            return ops[type(node.op)](_eval(node.left), _eval(node.right))\n"
        "        if isinstance(node, _ast.UnaryOp) and type(node.op) in ops:\n"
        "            return ops[type(node.op)](_eval(node.operand))\n"
        "        raise ValueError('unsupported')\n"
        "    try:\n"
        "        tree = _ast.parse(e, mode='eval')\n"
        "        return str(_eval(tree))\n"
        "    except Exception:\n"
        "        return 'تعذر الحساب'\n\n"
        "def time_now() -> str:\n"
        "    return datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')\n\n"
        "def echo(text: str) -> str:\n"
        "    return text or '—'\n\n"
        "def random_pick(text: str) -> str:\n"
        "    parts = [p.strip() for p in (text or '').split(',') if p.strip()]\n"
        "    return random.choice(parts) if parts else 'أدخل عناصر مفصولة بفاصلة'\n\n"
        "def short_note(user_id: int, text: str) -> int:\n"
        "    return _add(user_id, 'short_note', text)\n\n"
        "def stats_basic() -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        n = conn.execute("SELECT COUNT(*) AS c FROM extras_kv").fetchone()["c"]\n'
        "    return f'سجلات extras: {n}'\n"
    )




def _emit_reminders_service() -> str:
    """Lean, real reminders runtime — never a stub. Used when remind_* is selected."""
    return (
        '"""Reminders service — sqlite-backed due reminders."""\n'
        "from __future__ import annotations\n\n"
        "import re\n"
        "import time\n"
        "from datetime import datetime, timedelta, timezone\n\n"
        "from app.db import connect, init_db\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n\n"
        "def _parse_due(text: str) -> tuple[str, int]:\n"
        '    """Extract body + due unix ts. Default +1h if no time found."""\n'
        "    raw = (text or '').strip()\n"
        "    now = int(time.time())\n"
        "    due = now + 3600\n"
        "    body = raw\n"
        "    m = re.search(\n"
        "        r'(?:بعد\\s*)?(\\d+)\\s*(دقيقة|دقائق|minute|minutes|min|m|ساعة|ساعات|hour|hours|h|يوم|أيام|day|days|d)\\b',\n"
        "        raw, re.I,\n"
        "    )\n"
        "    if m:\n"
        "        n = int(m.group(1))\n"
        "        unit = m.group(2).lower()\n"
        "        if unit in {'دقيقة', 'دقائق', 'minute', 'minutes', 'min', 'm'}:\n"
        "            due = now + n * 60\n"
        "        elif unit in {'ساعة', 'ساعات', 'hour', 'hours', 'h'}:\n"
        "            due = now + n * 3600\n"
        "        else:\n"
        "            due = now + n * 86400\n"
        "        body = (raw[: m.start()] + raw[m.end():]).strip(' -–—,:،') or raw\n"
        "    m2 = re.search(r'\\b(\\d{1,2}):(\\d{2})\\s*(am|pm)?\\b', raw, re.I)\n"
        "    if m2:\n"
        "        hh, mm = int(m2.group(1)), int(m2.group(2))\n"
        "        ap = (m2.group(3) or '').lower()\n"
        "        if ap == 'pm' and hh < 12:\n"
        "            hh += 12\n"
        "        if ap == 'am' and hh == 12:\n"
        "            hh = 0\n"
        "        dt = datetime.now(timezone.utc).astimezone()\n"
        "        target = dt.replace(hour=min(hh, 23), minute=min(mm, 59), second=0, microsecond=0)\n"
        "        if target.timestamp() <= dt.timestamp():\n"
        "            target = target + timedelta(days=1)\n"
        "        due = int(target.timestamp())\n"
        "        body = (raw[: m2.start()] + raw[m2.end():]).strip(' -–—,:،') or raw\n"
        "    if not body:\n"
        "        body = raw or 'تذكير'\n"
        "    return body[:500], due\n\n\n"
        "def set_reminder(user_id: int, text: str, chat_id: int = 0) -> int:\n"
        "    ensure()\n"
        "    body, due_ts = _parse_due(text)\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO reminders (user_id, chat_id, body, due_ts, fired) VALUES (?, ?, ?, ?, 0)',\n"
        "            (int(user_id), int(chat_id or user_id), body, int(due_ts)),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return int(cur.lastrowid)\n\n\n"
        "def list_reminders(user_id: int) -> list[dict]:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            'SELECT id, body, due_ts, fired FROM reminders '\n"
        "            'WHERE user_id = ? AND fired = 0 ORDER BY due_ts ASC, id ASC',\n"
        "            (int(user_id),),\n"
        "        ).fetchall()\n"
        "    out = []\n"
        "    for r in rows:\n"
        "        d = dict(r)\n"
        "        due = int(d.get('due_ts') or 0)\n"
        "        d['remain_min'] = max(0, due - int(time.time())) // 60\n"
        "        out.append(d)\n"
        "    return out\n\n\n"
        "def clear_reminders(user_id: int) -> int:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'UPDATE reminders SET fired = 1 WHERE user_id = ? AND fired = 0',\n"
        "            (int(user_id),),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return int(cur.rowcount)\n\n\n"
        "def list_due_reminders(now_ts: int | None = None, limit: int = 50) -> list[dict]:\n"
        "    ensure()\n"
        "    now = int(now_ts if now_ts is not None else time.time())\n"
        "    lim = max(1, min(int(limit or 20), 50))\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            'SELECT id, user_id, chat_id, body, due_ts FROM reminders '\n"
        "            'WHERE fired = 0 AND due_ts > 0 AND due_ts <= ? '\n"
        "            'ORDER BY due_ts ASC LIMIT ?',\n"
        "            (now, lim),\n"
        "        ).fetchall()\n"
        "    return [dict(r) for r in rows]\n\n\n"
        "def mark_reminder_fired(reminder_id: int) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'UPDATE reminders SET fired = 1 WHERE id = ?',\n"
        "            (int(reminder_id),),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return cur.rowcount > 0\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        '    """Compat for handlers that call act(\'reminders\', ...)."""\n'
        "    entity = (entity or '').lower()\n"
        "    method = (method or '').lower()\n"
        "    if entity not in {'reminders', 'reminder'}:\n"
        "        return f'{method} is not available in this bot build'\n"
        "    if method in {'set_reminder', 'set', 'add'}:\n"
        "        rid = set_reminder(user_id, text or 'تذكير')\n"
        "        return f'تم ضبط التذكير #{rid}'\n"
        "    if method in {'list_reminders', 'list'}:\n"
        "        items = list_reminders(user_id)\n"
        "        if not items:\n"
        "            return 'لا توجد تذكيرات مفتوحة'\n"
        "        return '\\n'.join(f\"#{i['id']} خلال {i.get('remain_min', 0)} د — {i['body']}\" for i in items)\n"
        "    if method in {'clear_reminders', 'clear'}:\n"
        "        n = clear_reminders(user_id)\n"
        "        return f'تم إغلاق {n} تذكير'\n"
        "    return f'{method} is not available in this bot build'\n"
    )


def _emit_booking_service() -> str:
    """Lean booking runtime (sqlite)."""
    return (
        '"""Booking service — simple slot bookings."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n\n"
        "def book_slot(user_id: int, text: str = '', chat_id: int = 0) -> str:\n"
        "    ensure()\n"
        "    body = (text or 'موعد').strip()[:300] or 'موعد'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO bookings (user_id, chat_id, body, status) VALUES (?, ?, ?, ?)',\n"
        "            (int(user_id), int(chat_id or user_id), body, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم الحجز #{int(cur.lastrowid)}: {body}'\n\n\n"
        "def list_bookings(user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT id, body, status FROM bookings WHERE user_id = ? AND status = 'open' ORDER BY id DESC\",\n"
        "            (int(user_id),),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return 'لا توجد حجوزات مفتوحة'\n"
        "    return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows)\n\n\n"
        "def cancel_booking(user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    try:\n"
        "        bid = int((text or '').strip().split()[0])\n"
        "    except (ValueError, IndexError):\n"
        "        return 'الاستخدام: /bookcancel <رقم_الحجز>'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            \"UPDATE bookings SET status = 'cancelled' WHERE id = ? AND user_id = ? AND status = 'open'\",\n"
        "            (bid, int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return 'تم إلغاء الحجز' if cur.rowcount else 'الحجز غير موجود'\n\n\n"
        "def admin_list(user_id: int = 0, text: str = '') -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT id, user_id, body, status FROM bookings ORDER BY id DESC LIMIT 30\"\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return 'لا حجوزات'\n"
        "    return '\\n'.join(f\"#{r['id']} u{r['user_id']} [{r['status']}] {r['body']}\" for r in rows)\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    m = (method or '').lower()\n"
        "    if m in {'book_slot', 'book', 'add'}:\n"
        "        return book_slot(user_id, text)\n"
        "    if m in {'list_bookings', 'list', 'my'}:\n"
        "        return list_bookings(user_id, text)\n"
        "    if m in {'cancel_booking', 'cancel'}:\n"
        "        return cancel_booking(user_id, text)\n"
        "    if m in {'admin_list'}:\n"
        "        return admin_list(user_id, text)\n"
        "    return f'{method} is not available in this bot build'\n"
    )


def _emit_clinic_service() -> str:
    """Lean clinic appointments runtime (sqlite)."""
    return (
        '"""Clinic appointments service."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n\n"
        "def book(user_id: int, text: str = '', chat_id: int = 0) -> str:\n"
        "    ensure()\n"
        "    body = (text or 'موعد طبي').strip()[:300] or 'موعد طبي'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO clinic_appts (user_id, chat_id, body, status) VALUES (?, ?, ?, ?)',\n"
        "            (int(user_id), int(chat_id or user_id), body, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم حجز الموعد الطبي #{int(cur.lastrowid)}: {body}'\n\n\n"
        "def slots(user_id: int = 0, text: str = '') -> str:\n"
        "    return (\n"
        "        'المواعيد المتاحة (تجريبي):\\n'\n"
        "        '• غداً 10:00\\n• غداً 12:00\\n• بعد غد 16:00\\n'\n"
        "        'احجز بـ /clinicbook مع وصف الموعد'\n"
        "    )\n\n\n"
        "def cancel(user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    try:\n"
        "        aid = int((text or '').strip().split()[0])\n"
        "    except (ValueError, IndexError):\n"
        "        return 'الاستخدام: /cliniccancel <رقم_الموعد>'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            \"UPDATE clinic_appts SET status = 'cancelled' WHERE id = ? AND user_id = ? AND status = 'open'\",\n"
        "            (aid, int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return 'تم إلغاء الموعد' if cur.rowcount else 'الموعد غير موجود'\n\n\n"
        "def my_appointments(user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT id, body, status FROM clinic_appts WHERE user_id = ? AND status = 'open' ORDER BY id DESC\",\n"
        "            (int(user_id),),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return 'لا مواعيد مفتوحة'\n"
        "    return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows)\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    m = (method or '').lower()\n"
        "    if m in {'book', 'book_slot', 'add'}:\n"
        "        return book(user_id, text)\n"
        "    if m in {'slots', 'list_slots'}:\n"
        "        return slots(user_id, text)\n"
        "    if m in {'cancel'}:\n"
        "        return cancel(user_id, text)\n"
        "    if m in {'my_appointments', 'my', 'list'}:\n"
        "        return my_appointments(user_id, text)\n"
        "    return f'{method} is not available in this bot build'\n"
    )


def _emit_lean_generic_service() -> str:
    """Working generic.act store — never a dead stub. Used when fat runtime is not selected."""
    return (
        '"""Lean generic service — sqlite act() store for any entity/method."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            'CREATE TABLE IF NOT EXISTS generic_kv ('\n"
        "            'id INTEGER PRIMARY KEY AUTOINCREMENT, '\n"
        "            'user_id INTEGER NOT NULL DEFAULT 0, '\n"
        "            'entity TEXT NOT NULL, '\n"
        "            'method TEXT NOT NULL DEFAULT \\'\\', '\n"
        "            'body TEXT NOT NULL, '\n"
        "            'status TEXT NOT NULL DEFAULT \\'open\\', '\n"
        "            'created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'\n"
        "        )\n"
        "        conn.commit()\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    ent = (entity or 'item').strip().lower() or 'item'\n"
        "    meth = (method or '').strip().lower()\n"
        "    body = (text or '').strip()[:500]\n"
        "    uid = int(user_id)\n\n"
        "    # create / set / add / book / open\n"
        "    if meth in {\n"
        "        'add', 'set', 'create', 'book', 'book_slot', 'open', 'capture',\n"
        "        'set_reminder', 'lead_capture', 'submit', 'start', 'enroll', 'rsvp',\n"
        "    } or meth.endswith('_add') or meth.endswith('_create') or meth.endswith('_set'):\n"
        "        with connect() as conn:\n"
        "            cur = conn.execute(\n"
        "                'INSERT INTO generic_kv (user_id, entity, method, body, status) VALUES (?, ?, ?, ?, ?)',\n"
        "                (uid, ent, meth, body or ent, 'open'),\n"
        "            )\n"
        "            conn.commit()\n"
        "            return f'تم التسجيل #{int(cur.lastrowid)}'\n\n"
        "    # list / my / status\n"
        "    if meth in {\n"
        "        'list', 'list_open', 'my', 'my_appointments', 'list_bookings', 'list_reminders',\n"
        "        'lead_list', 'status', 'view', 'overview',\n"
        "    } or meth.startswith('list') or meth.startswith('my_'):\n"
        "        with connect() as conn:\n"
        "            rows = conn.execute(\n"
        "                \"SELECT id, body, status FROM generic_kv \"\n"
        "                \"WHERE user_id = ? AND entity = ? AND status = 'open' ORDER BY id DESC LIMIT 30\",\n"
        "                (uid, ent),\n"
        "            ).fetchall()\n"
        "        if not rows:\n"
        "            return 'لا توجد عناصر'\n"
        "        return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows)\n\n"
        "    # cancel / close / delete / clear\n"
        "    if meth in {'cancel', 'cancel_booking', 'close', 'delete', 'clear', 'clear_reminders'} or meth.startswith('cancel'):\n"
        "        parts = body.split()\n"
        "        try:\n"
        "            iid = int(parts[0]) if parts else 0\n"
        "        except ValueError:\n"
        "            iid = 0\n"
        "        with connect() as conn:\n"
        "            if iid:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE generic_kv SET status = 'closed' WHERE id = ? AND user_id = ?\",\n"
        "                    (iid, uid),\n"
        "                )\n"
        "            else:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE generic_kv SET status = 'closed' WHERE user_id = ? AND entity = ? AND status = 'open'\",\n"
        "                    (uid, ent),\n"
        "                )\n"
        "            conn.commit()\n"
        "            return f'تم الإغلاق ({int(cur.rowcount)})'\n\n"
        "    # default: store note under entity\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO generic_kv (user_id, entity, method, body, status) VALUES (?, ?, ?, ?, ?)',\n"
        "            (uid, ent, meth or 'note', body or meth or ent, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم الحفظ #{int(cur.lastrowid)}'\n\n\n"
        "def list_due_reminders(now_ts=None, limit: int = 50):\n"
        "    return []\n\n\n"
        "def mark_reminder_fired(reminder_id: int) -> bool:\n"
        "    return False\n"
    )


def _emit_lean_named_service(name: str) -> str:
    """Working named service module that delegates to lean patterns via local sqlite."""
    safe = "".join(ch for ch in (name or "svc") if ch.isalnum() or ch == "_") or "svc"
    return (
        f'"""Auto service `{safe}` — working sqlite-backed handlers."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n"
        f"_ENTITY = {safe!r}\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            'CREATE TABLE IF NOT EXISTS entity_kv ('\n"
        "            'id INTEGER PRIMARY KEY AUTOINCREMENT, '\n"
        "            'user_id INTEGER NOT NULL DEFAULT 0, '\n"
        "            'entity TEXT NOT NULL, '\n"
        "            'body TEXT NOT NULL, '\n"
        "            'status TEXT NOT NULL DEFAULT \\'open\\', '\n"
        "            'created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'\n"
        "        )\n"
        "        conn.commit()\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    ent = (entity or _ENTITY).strip().lower() or _ENTITY\n"
        "    meth = (method or '').strip().lower()\n"
        "    body = (text or '').strip()[:500]\n"
        "    uid = int(user_id)\n"
        "    if meth in {'list', 'my', 'view', 'status'} or meth.startswith('list') or meth.startswith('my_'):\n"
        "        with connect() as conn:\n"
        "            rows = conn.execute(\n"
        "                \"SELECT id, body FROM entity_kv WHERE user_id = ? AND entity = ? AND status = 'open' ORDER BY id DESC LIMIT 30\",\n"
        "                (uid, ent),\n"
        "            ).fetchall()\n"
        "        return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows) if rows else 'لا توجد عناصر'\n"
        "    if meth in {'cancel', 'close', 'delete', 'clear'} or meth.startswith('cancel'):\n"
        "        parts = body.split()\n"
        "        try:\n"
        "            iid = int(parts[0]) if parts else 0\n"
        "        except ValueError:\n"
        "            iid = 0\n"
        "        with connect() as conn:\n"
        "            if iid:\n"
        "                cur = conn.execute(\"UPDATE entity_kv SET status='closed' WHERE id=? AND user_id=?\", (iid, uid))\n"
        "            else:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE entity_kv SET status='closed' WHERE user_id=? AND entity=? AND status='open'\",\n"
        "                    (uid, ent),\n"
        "                )\n"
        "            conn.commit()\n"
        "            return f'تم الإغلاق ({int(cur.rowcount)})'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO entity_kv (user_id, entity, body, status) VALUES (?, ?, ?, ?)',\n"
        "            (uid, ent, body or meth or ent, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم الحفظ #{int(cur.lastrowid)}'\n\n\n"
        "def __getattr__(item: str):\n"
        "    def _call(*args, **kwargs):\n"
        "        uid = 0\n"
        "        text = ''\n"
        "        if args:\n"
        "            uid = int(args[0]) if str(args[0]).lstrip('-').isdigit() else 0\n"
        "            if len(args) > 1:\n"
        "                text = str(args[1])\n"
        "        return act(_ENTITY, item, uid, text)\n"
        "    return _call\n"
    )


def _emit_pubg() -> str:
    """PUBG / group gaming: players, teams, matches, points, tournaments."""
    return (
        "\"\"\"PUBG service — players, teams, matches, points, tournaments (per chat).\"\"\"\n"
        "from __future__ import annotations\n"
        "\n"
        "import time\n"
        "from app.db import connect, init_db\n"
        "\n"
        "\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_players (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"ign TEXT NOT NULL DEFAULT '', team TEXT NOT NULL DEFAULT '', \"\n"
        "            \"points INTEGER NOT NULL DEFAULT 0, matches INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"wins INTEGER NOT NULL DEFAULT 0, kills INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_matches (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"note TEXT NOT NULL DEFAULT '', points_awarded INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, created_by INTEGER NOT NULL DEFAULT 0)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_tournaments (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, created_by INTEGER NOT NULL DEFAULT 0)\"\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def register_player(chat_id: int, user_id: int, ign: str = \"\") -> str:\n"
        "    ensure()\n"
        "    ign = (ign or f\"player_{user_id}\")[:64]\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO pubg_players (chat_id, user_id, ign, created_at) VALUES (?, ?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET ign = excluded.ign\",\n"
        "            (int(chat_id), int(user_id), ign, int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تم تسجيل اللاعب: {ign}\"\n"
        "\n"
        "\n"
        "def list_players(chat_id: int, limit: int = 30) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT user_id, ign, team, points, matches, wins, kills FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? ORDER BY points DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 50))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا يوجد لاعبون مسجلون\"\n"
        "    lines = [f\"• {r['ign']} (uid={r['user_id']}) team={r['team'] or '-'} pts={r['points']} W={r['wins']} K={r['kills']}\" for r in rows]\n"
        "    return \"قائمة اللاعبين:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "\n"
        "def set_team(chat_id: int, user_id: int, team: str) -> str:\n"
        "    ensure()\n"
        "    team = (team or \"\")[:32]\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT user_id FROM pubg_players WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        if not row:\n"
        "            conn.execute(\n"
        "                \"INSERT INTO pubg_players (chat_id, user_id, ign, team, created_at) VALUES (?, ?, ?, ?, ?)\",\n"
        "                (int(chat_id), int(user_id), f\"player_{user_id}\", team, int(time.time())),\n"
        "            )\n"
        "        else:\n"
        "            conn.execute(\n"
        "                \"UPDATE pubg_players SET team = ? WHERE chat_id = ? AND user_id = ?\",\n"
        "                (team, int(chat_id), int(user_id)),\n"
        "            )\n"
        "        conn.commit()\n"
        "    return f\"فريق {user_id}: {team or '-'}\"\n"
        "\n"
        "\n"
        "def list_teams(chat_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT team, COUNT(*) AS n, SUM(points) AS pts FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? AND team != '' GROUP BY team ORDER BY pts DESC\",\n"
        "            (int(chat_id),),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا توجد فرق\"\n"
        "    return \"الفرق:\\n\" + \"\\n\".join(f\"• {r['team']}: members={r['n']} pts={r['pts']}\" for r in rows)\n"
        "\n"
        "\n"
        "def record_match(chat_id: int, admin_id: int, note: str = \"\", points: int = 10, winner_id: int = 0, kills: int = 0) -> str:\n"
        "    ensure()\n"
        "    points = max(0, min(int(points), 1000))\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO pubg_matches (chat_id, note, points_awarded, created_at, created_by) VALUES (?, ?, ?, ?, ?)\",\n"
        "            (int(chat_id), (note or \"\")[:200], points, int(time.time()), int(admin_id)),\n"
        "        )\n"
        "        if winner_id:\n"
        "            conn.execute(\n"
        "                \"INSERT INTO pubg_players (chat_id, user_id, ign, points, matches, wins, kills, created_at) \"\n"
        "                \"VALUES (?, ?, ?, ?, 1, 1, ?, ?) \"\n"
        "                \"ON CONFLICT(chat_id, user_id) DO UPDATE SET \"\n"
        "                \"points = points + excluded.points, matches = matches + 1, wins = wins + 1, kills = kills + excluded.kills\",\n"
        "                (int(chat_id), int(winner_id), f\"player_{winner_id}\", points, int(kills), int(time.time())),\n"
        "            )\n"
        "        conn.commit()\n"
        "    return f\"سُجلت مباراة (+{points} نقطة)\" + (f\" للفائز {winner_id}\" if winner_id else \"\")\n"
        "\n"
        "\n"
        "def top_players(chat_id: int, limit: int = 10) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT ign, user_id, points, wins, kills FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? ORDER BY points DESC, wins DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 25))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا يوجد ترتيب بعد\"\n"
        "    lines = [f\"{i+1}. {r['ign']} — {r['points']} pts | W={r['wins']} K={r['kills']}\" for i, r in enumerate(rows)]\n"
        "    return \"Top Players:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "\n"
        "def player_stats(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT * FROM pubg_players WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    if not row:\n"
        "        return \"اللاعب غير مسجل — استخدم /pubg_register\"\n"
        "    return (\n"
        "        f\"إحصائيات {row['ign']}:\\n\"\n"
        "        f\"النقاط: {row['points']}\\nالمباريات: {row['matches']}\\n\"\n"
        "        f\"الانتصارات: {row['wins']}\\nالقتل: {row['kills']}\\nالفريق: {row['team'] or '-'}\"\n"
        "    )\n"
        "\n"
        "\n"
        "def create_tournament(chat_id: int, admin_id: int, title: str) -> str:\n"
        "    ensure()\n"
        "    title = (title or \"Tournament\").strip()[:80]\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            \"INSERT INTO pubg_tournaments (chat_id, title, status, created_at, created_by) VALUES (?, ?, 'open', ?, ?)\",\n"
        "            (int(chat_id), title, int(time.time()), int(admin_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "        tid = int(cur.lastrowid)\n"
        "    return f\"بطولة #{tid}: {title} (مفتوحة)\"\n"
    )

