"""Mass capability expansion toward launch scale (30k complex systems).

Generates structured, deterministic capability keys from vertical × action
templates. Shared service/method patterns keep zero-AI codegen stable.
"""
from __future__ import annotations

from .registry import CAPABILITIES, Capability, _add, _c

# ── shared action vocabularies ──────────────────────────────────────────
CRUD = (
    ("list", "قائمة", "List"),
    ("view", "عرض", "View"),
    ("create", "إنشاء", "Create"),
    ("update", "تحديث", "Update"),
    ("delete", "حذف", "Delete"),
    ("search", "بحث", "Search"),
    ("filter", "تصفية", "Filter"),
    ("export", "تصدير", "Export"),
    ("import_data", "استيراد", "Import"),
    ("archive", "أرشفة", "Archive"),
    ("restore", "استعادة", "Restore"),
    ("duplicate", "نسخ", "Duplicate"),
    ("share", "مشاركة", "Share"),
    ("pin", "تثبيت", "Pin"),
    ("unpin", "إلغاء تثبيت", "Unpin"),
    ("favorite", "مفضلة", "Favorite"),
    ("unfavorite", "إزالة من المفضلة", "Unfavorite"),
    ("stats", "إحصاء", "Stats"),
    ("history", "سجل", "History"),
    ("audit", "تدقيق", "Audit"),
)

WORKFLOW = (
    ("submit", "إرسال", "Submit"),
    ("approve", "قبول", "Approve"),
    ("reject", "رفض", "Reject"),
    ("assign", "تعيين", "Assign"),
    ("claim", "استلام", "Claim"),
    ("release", "تحرير", "Release"),
    ("escalate", "تصعيد", "Escalate"),
    ("close", "إغلاق", "Close"),
    ("reopen", "إعادة فتح", "Reopen"),
    ("schedule", "جدولة", "Schedule"),
    ("reschedule", "إعادة جدولة", "Reschedule"),
    ("cancel", "إلغاء", "Cancel"),
    ("postpone", "تأجيل", "Postpone"),
    ("remind", "تذكير", "Remind"),
    ("notify", "إشعار", "Notify"),
)

COMMERCE = (
    ("buy", "شراء", "Buy"),
    ("sell", "بيع", "Sell"),
    ("quote", "عرض سعر", "Quote"),
    ("invoice", "فاتورة", "Invoice"),
    ("refund", "استرجاع", "Refund"),
    ("discount", "خصم", "Discount"),
    ("coupon", "كوبون", "Coupon"),
    ("checkout", "إتمام شراء", "Checkout"),
    ("cart_add", "إضافة سلة", "Cart add"),
    ("cart_remove", "حذف من السلة", "Cart remove"),
    ("wishlist", "مفضلة شراء", "Wishlist"),
    ("review", "تقييم", "Review"),
    ("rate", "نجوم", "Rate"),
    ("ship", "شحن", "Ship"),
    ("track", "تتبع", "Track"),
    ("fulfill", "تنفيذ طلب", "Fulfill"),
    ("stock", "مخزون", "Stock"),
    ("price", "تسعير", "Price"),
    ("tax", "ضريبة", "Tax"),
    ("currency", "عملة", "Currency"),
)

SOCIAL = (
    ("follow", "متابعة", "Follow"),
    ("unfollow", "إلغاء متابعة", "Unfollow"),
    ("like", "إعجاب", "Like"),
    ("unlike", "إلغاء إعجاب", "Unlike"),
    ("comment", "تعليق", "Comment"),
    ("reply", "رد", "Reply"),
    ("repost", "إعادة نشر", "Repost"),
    ("report", "بلاغ", "Report"),
    ("block", "حظر", "Block"),
    ("unblock", "فك حظر", "Unblock"),
    ("mute", "كتم", "Mute"),
    ("unmute", "إلغاء كتم", "Unmute"),
    ("invite", "دعوة", "Invite"),
    ("join", "انضمام", "Join"),
    ("leave", "مغادرة", "Leave"),
)

GAMING = (
    ("play", "لعب", "Play"),
    ("pause", "إيقاف", "Pause"),
    ("resume", "استئناف", "Resume"),
    ("score", "نتيجة", "Score"),
    ("rank", "ترتيب", "Rank"),
    ("reward", "مكافأة", "Reward"),
    ("quest", "مهمة", "Quest"),
    ("badge", "شارة", "Badge"),
    ("level_up", "ترقية مستوى", "Level up"),
    ("streak", "سلسلة", "Streak"),
    ("checkin", "تسجيل يومي", "Check-in"),
    ("leaderboard", "متصدرين", "Leaderboard"),
)

ADMIN = (
    ("config", "إعداد", "Config"),
    ("toggle", "تفعيل/إيقاف", "Toggle"),
    ("broadcast", "إذاعة", "Broadcast"),
    ("ban", "حظر", "Ban"),
    ("unban", "فك حظر", "Unban"),
    ("role_set", "تعيين دور", "Set role"),
    ("audit_log", "سجل تدقيق", "Audit log"),
    ("metrics", "مقاييس", "Metrics"),
    ("health", "صحة النظام", "Health"),
    ("backup", "نسخ احتياطي", "Backup"),
    ("restore_backup", "استعادة نسخة", "Restore backup"),
    ("feature_flag", "علم ميزة", "Feature flag"),
)

# Vertical domains: (prefix, service, category, ar_name, en_name)

# Complex systems — methods already executed by generic.act / market
COMPLEX_SAAS = (
    ("list", "قائمة", "List"),
    ("view", "عرض", "View"),
    ("create", "إنشاء", "Create"),
    ("update", "تحديث", "Update"),
    ("delete", "حذف", "Delete"),
    ("search", "بحث", "Search"),
    ("filter", "تصفية", "Filter"),
    ("assign", "تعيين", "Assign"),
    ("approve", "موافقة", "Approve"),
    ("reject", "رفض", "Reject"),
    ("status", "حالة", "Status"),
    ("stats", "إحصائيات", "Stats"),
    ("history", "سجل", "History"),
    ("export", "تصدير", "Export"),
    ("archive", "أرشفة", "Archive"),
    ("restore", "استعادة", "Restore"),
    ("share", "مشاركة", "Share"),
    ("subscribe", "اشتراك", "Subscribe"),
    ("renew", "تجديد", "Renew"),
    ("upgrade", "ترقية", "Upgrade"),
    ("downgrade", "تخفيض", "Downgrade"),
    ("start_trial", "تجربة", "Start trial"),
    ("cancel", "إلغاء", "Cancel"),
    ("invite", "دعوة", "Invite"),
    ("revoke", "سحب", "Revoke"),
    ("set_role", "تعيين دور", "Set role"),
    ("webhook_set", "ضبط ويب هوك", "Set webhook"),
    ("webhook_test", "اختبار ويب هوك", "Test webhook"),
    ("feature_flag", "علم ميزة", "Feature flag"),
    ("audit", "تدقيق", "Audit"),
    ("backup", "نسخ احتياطي", "Backup"),
    ("config", "إعداد", "Config"),
    ("dashboard", "لوحة", "Dashboard"),
    ("usage", "استخدام", "Usage"),
    ("quota", "حصة", "Quota"),
    ("seat_add", "إضافة مقعد", "Add seat"),
    ("seat_remove", "إزالة مقعد", "Remove seat"),
    ("sso_info", "دخول موحد", "SSO info"),
    ("api_token_issue", "إصدار توكن", "Issue API token"),
)

COMPLEX_MARKETPLACE = (
    ("list", "قائمة", "List"),
    ("view", "عرض", "View"),
    ("create", "إنشاء", "Create"),
    ("update", "تحديث", "Update"),
    ("delete", "حذف", "Delete"),
    ("search", "بحث", "Search"),
    ("filter", "تصفية", "Filter"),
    ("status", "حالة", "Status"),
    ("stats", "إحصائيات", "Stats"),
    ("history", "سجل", "History"),
    ("export", "تصدير", "Export"),
    ("approve", "موافقة", "Approve"),
    ("reject", "رفض", "Reject"),
    ("assign", "تعيين", "Assign"),
    ("bid", "مزايدة", "Bid"),
    ("buy", "شراء", "Buy"),
    ("sell", "بيع", "Sell"),
    ("checkout", "إتمام شراء", "Checkout"),
    ("ship", "شحن", "Ship"),
    ("track", "تتبع", "Track"),
    ("review", "تقييم", "Review"),
    ("favorite", "مفضلة", "Favorite"),
    ("unfavorite", "إزالة مفضلة", "Unfavorite"),
    ("share", "مشاركة", "Share"),
    ("report", "بلاغ", "Report"),
    ("dispute", "نزاع", "Dispute"),
    ("refund", "استرجاع", "Refund"),
    ("payout", "صرف", "Payout"),
    ("commission", "عمولة", "Commission"),
    ("vendor_register", "تسجيل بائع", "Vendor register"),
    ("catalog", "كتالوج", "Catalog"),
    ("offer", "عرض", "Offer"),
    ("accept", "قبول", "Accept"),
    ("message", "رسالة", "Message"),
    ("escalate", "تصعيد", "Escalate"),
)

COMPLEX_LOGISTICS = (
    ("list", "قائمة", "List"),
    ("view", "عرض", "View"),
    ("create", "إنشاء", "Create"),
    ("update", "تحديث", "Update"),
    ("delete", "حذف", "Delete"),
    ("search", "بحث", "Search"),
    ("filter", "تصفية", "Filter"),
    ("status", "حالة", "Status"),
    ("stats", "إحصائيات", "Stats"),
    ("history", "سجل", "History"),
    ("track", "تتبع", "Track"),
    ("schedule", "جدولة", "Schedule"),
    ("assign", "تعيين", "Assign"),
    ("approve", "موافقة", "Approve"),
    ("reject", "رفض", "Reject"),
    ("ship", "شحن", "Ship"),
    ("pickup", "استلام", "Pickup"),
    ("deliver", "تسليم", "Deliver"),
    ("return_item", "إرجاع", "Return"),
    ("reroute", "إعادة توجيه", "Reroute"),
    ("scan", "مسح", "Scan"),
    ("pack", "تعبئة", "Pack"),
    ("dispatch", "إرسال", "Dispatch"),
    ("arrive", "وصول", "Arrive"),
    ("depart", "مغادرة", "Depart"),
    ("capacity", "سعة", "Capacity"),
    ("eta", "وقت وصول", "ETA"),
    ("pod", "إثبات تسليم", "Proof of delivery"),
    ("exception", "استثناء", "Exception"),
    ("export", "تصدير", "Export"),
    ("archive", "أرشفة", "Archive"),
    ("restore", "استعادة", "Restore"),
)

COMPLEX_FINANCE = (
    ("list", "قائمة", "List"),
    ("view", "عرض", "View"),
    ("create", "إنشاء", "Create"),
    ("update", "تحديث", "Update"),
    ("delete", "حذف", "Delete"),
    ("search", "بحث", "Search"),
    ("filter", "تصفية", "Filter"),
    ("status", "حالة", "Status"),
    ("stats", "إحصائيات", "Stats"),
    ("history", "سجل", "History"),
    ("export", "تصدير", "Export"),
    ("approve", "موافقة", "Approve"),
    ("reject", "رفض", "Reject"),
    ("assign", "تعيين", "Assign"),
    ("pay", "دفع", "Pay"),
    ("refund", "استرجاع", "Refund"),
    ("transfer", "تحويل", "Transfer"),
    ("topup", "شحن", "Top up"),
    ("withdraw", "سحب", "Withdraw"),
    ("invoice", "فاتورة", "Invoice"),
    ("reconcile", "تسوية", "Reconcile"),
    ("ledger", "دفتر", "Ledger"),
    ("balance", "رصيد", "Balance"),
    ("fee", "رسوم", "Fee"),
    ("tax", "ضريبة", "Tax"),
    ("payout", "صرف", "Payout"),
    ("settle", "تصفية", "Settle"),
    ("chargeback", "استرداد بنكي", "Chargeback"),
    ("limit", "حد", "Limit"),
    ("kyc_check", "تحقق هوية", "KYC check"),
    ("freeze", "تجميد", "Freeze"),
    ("unfreeze", "إلغاء تجميد", "Unfreeze"),
    ("statement", "كشف حساب", "Statement"),
    ("audit", "تدقيق", "Audit"),
)

VERTICALS: list[tuple[str, str, str, str, str]] = [
    ("inv", "inventory", "inventory", "مخزون", "Inventory"),
    ("sku", "catalog", "catalog", "صنف", "SKU"),
    ("ord", "orders", "orders", "طلب", "Order"),
    ("pay", "billing", "billing", "دفعة", "Payment"),
    ("sub", "subs", "subs", "اشتراك", "Subscription"),
    ("mem", "members", "members", "عضو", "Member"),
    ("tkt", "tickets2", "tickets2", "تذكرة", "Ticket"),
    ("lead", "leads", "leads", "عميل", "Lead"),
    ("deal", "deals", "deals", "صفقة", "Deal"),
    ("camp", "campaigns", "campaigns", "حملة", "Campaign"),
    ("coup", "coupons", "coupons", "كوبون", "Coupon"),
    ("aff", "affiliate", "affiliate", "شريك", "Affiliate"),
    ("ref", "refs", "refs", "إحالة", "Referral"),
    ("pts", "loyalty", "loyalty", "نقاط", "Points"),
    ("wal", "wallets", "wallets", "محفظة", "Wallet"),
    ("gift", "gifts", "gifts", "هدية", "Gift"),
    ("evt", "events2", "events2", "فعالية", "Event"),
    ("rsvp", "rsvps", "rsvps", "حضور", "RSVP"),
    ("crs", "courses", "courses", "دورة", "Course"),
    ("lsn", "lessons", "lessons", "درس", "Lesson"),
    ("quiz", "quizzes", "quizzes", "اختبار", "Quiz"),
    ("job", "jobs2", "jobs2", "وظيفة", "Job"),
    ("app", "apps", "apps", "طلب توظيف", "Application"),
    ("prop", "props", "props", "عقار", "Property"),
    ("apt", "apts", "apts", "موعد", "Appointment"),
    ("gym", "gyms", "gyms", "حصة", "Session"),
    ("menu", "menus", "menus", "قائمة", "Menu"),
    ("dish", "dishes", "dishes", "طبق", "Dish"),
    ("tbl", "tables", "tables", "طاولة", "Table"),
    ("ship", "ships", "ships", "شحنة", "Shipment"),
    ("auc", "auctions2", "auctions2", "مزاد", "Auction"),
    ("bid", "bids", "bids", "مزايدة", "Bid"),
    ("post", "posts", "posts", "منشور", "Post"),
    ("cmt", "comments", "comments", "تعليق", "Comment"),
    ("feed", "feeds", "feeds", "خلاصة", "Feed"),
    ("grp", "groups2", "groups2", "مجموعة", "Group"),
    ("chn", "channels", "channels", "قناة", "Channel"),
    ("msg", "messages", "messages", "رسالة", "Message"),
    ("file", "files", "files", "ملف", "File"),
    ("doc", "docs", "docs", "مستند", "Document"),
    ("form", "forms2", "forms2", "نموذج", "Form"),
    ("surv", "surveys", "surveys", "استبيان", "Survey"),
    ("poll", "polls", "polls", "تصويت", "Poll"),
    ("kb", "kb2", "kb2", "معرفة", "KB"),
    ("faq", "faqs", "faqs", "أسئلة", "FAQ"),
    ("tag", "tags", "tags", "وسم", "Tag"),
    ("cat", "cats", "cats", "تصنيف", "Category"),
    ("brand", "brands", "brands", "علامة", "Brand"),
    ("store", "stores", "stores", "متجر", "Store"),
    ("wh", "warehouses", "warehouses", "مستودع", "Warehouse"),
    ("vendor", "vendors", "vendors", "مورد", "Vendor"),
    ("cust", "customers", "customers", "زبون", "Customer"),
    ("staff", "staff", "staff", "موظف", "Staff"),
    ("role", "roles", "roles", "دور", "Role"),
    ("perm", "perms", "perms", "صلاحية", "Permission"),
    ("notif", "notifs", "notifs", "تنبيه", "Notification"),
    ("tmpl", "templates", "templates", "قالب", "Template"),
    ("hook", "hooks", "hooks", "ويب هوك", "Webhook"),
    ("api", "apis", "apis", "واجهة", "API key"),
    ("log", "logs", "logs", "سجل", "Log"),
    ("metric", "metrics2", "metrics2", "مقياس", "Metric"),
    ("report", "reports", "reports", "تقرير", "Report"),
    ("invoice2", "invoices", "invoices", "فاتورة", "Invoice"),
    ("tax2", "taxes", "taxes", "ضريبة", "Tax"),
    ("curr", "currencies", "currencies", "عملة", "Currency"),
    ("lang2", "langs", "langs", "لغة", "Language"),
    ("theme", "themes", "themes", "سمة", "Theme"),
    ("badge2", "badges", "badges", "شارة", "Badge"),
    ("quest2", "quests", "quests", "مهمة", "Quest"),
    ("ach", "achievements", "achievements", "إنجاز", "Achievement"),
    ("tier", "tiers", "tiers", "مستوى", "Tier"),
    ("plan2", "plans2", "plans2", "خطة", "Plan"),
    ("addon", "addons", "addons", "إضافة", "Add-on"),
    ("bundle", "bundles", "bundles", "باقة", "Bundle"),
    ("promo", "promos", "promos", "عرض", "Promo"),
    ("flash", "flashsales", "flashsales", "عرض خاطف", "Flash sale"),
    ("wait", "waitlists2", "waitlists2", "انتظار", "Waitlist"),
    ("room", "rooms", "rooms", "غرفة", "Room"),
    ("seat", "seats", "seats", "مقعد", "Seat"),
    ("vehicle", "vehicles", "vehicles", "مركبة", "Vehicle"),
    ("route", "routes", "routes", "مسار", "Route"),
    ("stop", "stops", "stops", "محطة", "Stop"),
    ("driver", "drivers", "drivers", "سائق", "Driver"),
    ("rider", "riders", "riders", "راكب", "Rider"),
    ("pet", "pets", "pets", "حيوان", "Pet"),
    ("book2", "books", "books", "كتاب", "Book"),
    ("chapter", "chapters", "chapters", "فصل", "Chapter"),
    ("podcast", "podcasts", "podcasts", "بودكاست", "Podcast"),
    ("episode", "episodes", "episodes", "حلقة", "Episode"),
    ("stream", "streams", "streams", "بث", "Stream"),
    ("clip", "clips", "clips", "مقطع", "Clip"),
    ("asset", "assets", "assets", "أصل", "Asset"),
    ("license", "licenses", "licenses", "ترخيص", "License"),
    ("key2", "keys", "keys", "مفتاح", "Key"),
    ("token2", "tokens", "tokens", "رمز", "Token"),
    ("device", "devices", "devices", "جهاز", "Device"),
    ("sensor", "sensors", "sensors", "مستشعر", "Sensor"),
    ("alert2", "alerts", "alerts", "إنذار", "Alert"),
    ("incident2", "incidents", "incidents", "حادثة", "Incident"),
    ("sla2", "slas", "slas", "اتفاقية", "SLA"),
    ("contract", "contracts", "contracts", "عقد", "Contract"),
    ("invoice_item", "invoice_items", "invoice_items", "بند فاتورة", "Invoice item"),
    ("project", "projects", "projects", "مشروع", "Project"),
    ("task2", "tasks2", "tasks2", "مهمة عمل", "Work task"),
    ("sprint", "sprints", "sprints", "سبيرنت", "Sprint"),
    ("milestone", "milestones", "milestones", "معلم", "Milestone"),
    ("time_entry", "time_entries", "time_entries", "وقت", "Time entry"),
    ("expense", "expenses", "expenses", "مصروف", "Expense"),
    ("budget", "budgets", "budgets", "ميزانية", "Budget"),
    ("invoice_rec", "recurring", "recurring", "فاتورة دورية", "Recurring"),
    ("sub_item", "sub_items", "sub_items", "بند اشتراك", "Sub item"),
    ("credit_note", "credit_notes", "credit_notes", "إشعار دائن", "Credit note"),
    ("debit_note", "debit_notes", "debit_notes", "إشعار مدين", "Debit note"),
    ("refund2", "refunds2", "refunds2", "مرتجع", "Refund"),
    ("return2", "returns", "returns", "إرجاع", "Return"),
    ("exchange", "exchanges", "exchanges", "استبدال", "Exchange"),
    ("warranty", "warranties", "warranties", "ضمان", "Warranty"),
    ("service2", "services2", "services2", "خدمة", "Service"),
    ("package", "packages", "packages", "طرد", "Package"),
    ("label", "labels", "labels", "ملصق", "Label"),
    ("zone", "zones", "zones", "منطقة", "Zone"),
    ("rate2", "rates", "rates", "تعريفة", "Rate"),
    ("carrier", "carriers", "carriers", "ناقل", "Carrier"),
    ("pickup", "pickups", "pickups", "استلام", "Pickup"),
    ("dropoff", "dropoffs", "dropoffs", "تسليم", "Dropoff"),
    ("slot2", "slots", "slots", "فترة", "Slot"),
    ("calendar", "calendars", "calendars", "تقويم", "Calendar"),
    ("reminder2", "reminders2", "reminders2", "تذكير", "Reminder"),
    ("habit", "habits", "habits", "عادة", "Habit"),
    ("goal", "goals", "goals", "هدف", "Goal"),
    ("note2", "notes2", "notes2", "ملاحظة", "Note"),
    ("folder", "folders", "folders", "مجلد", "Folder"),
    ("link", "links", "links", "رابط", "Link"),
    ("qr", "qrs", "qrs", "رمز QR", "QR"),
    ("barcode", "barcodes", "barcodes", "باركود", "Barcode"),
    ("print2", "prints", "prints", "طباعة", "Print job"),
    ("scan", "scans", "scans", "مسح", "Scan"),
    ("ocr", "ocrs", "ocrs", "تعرف نص", "OCR job"),
    ("translate", "translates", "translates", "ترجمة", "Translate job"),
    ("voice", "voices", "voices", "صوت", "Voice note"),
    ("sticker", "stickers", "stickers", "ملصق", "Sticker"),
    ("emoji", "emojis", "emojis", "إيموجي", "Emoji pack"),
    ("theme2", "ui_themes", "ui_themes", "واجهة", "UI theme"),
    ("locale", "locales", "locales", "محلية", "Locale"),
    ("timezone", "timezones", "timezones", "منطقة زمنية", "Timezone"),
    ("holiday", "holidays", "holidays", "عطلة", "Holiday"),
    ("shift", "shifts", "shifts", "وردية", "Shift"),
    ("attendance", "attendance", "attendance", "حضور", "Attendance"),
    ("leave2", "leaves", "leaves", "إجازة", "Leave"),
    ("payroll", "payrolls", "payrolls", "رواتب", "Payroll"),
    ("invoice_pay", "invoice_pays", "invoice_pays", "سداد", "Invoice payment"),
    ("payout", "payouts", "payouts", "صرف", "Payout"),
    ("settlement", "settlements", "settlements", "تسوية", "Settlement"),
    ("chargeback", "chargebacks", "chargebacks", "استرداد قسري", "Chargeback"),
    ("dispute", "disputes", "disputes", "نزاع", "Dispute"),
    ("case", "cases", "cases", "قضية", "Case"),
    ("evidence", "evidence", "evidence", "دليل", "Evidence"),
    ("policy", "policies", "policies", "سياسة", "Policy"),
    ("consent", "consents", "consents", "موافقة", "Consent"),
    ("gdpr", "gdpr", "gdpr", "خصوصية", "GDPR request"),
    ("export2", "exports", "exports", "تصدير بيانات", "Data export"),
    ("import2", "imports", "imports", "استيراد بيانات", "Data import"),
    ("migration", "migrations", "migrations", "ترحيل", "Migration"),
    ("sync", "syncs", "syncs", "مزامنة", "Sync job"),
    ("queue", "queues", "queues", "طابور", "Queue"),
    ("job_run", "job_runs", "job_runs", "تشغيل", "Job run"),
    ("cron", "crons", "crons", "جدولة زمنية", "Cron"),
    ("worker", "workers", "workers", "عامل", "Worker"),
    ("cache", "caches", "caches", "ذاكرة مؤقتة", "Cache"),
    ("session2", "sessions", "sessions", "جلسة", "Session"),
    ("device2", "user_devices", "user_devices", "جهاز مستخدم", "User device"),
    ("push", "pushes", "pushes", "دفع إشعار", "Push"),
    ("email2", "emails", "emails", "بريد", "Email"),
    ("sms", "sms", "sms", "رسالة نصية", "SMS"),
    ("call", "calls", "calls", "مكالمة", "Call"),
    ("meeting", "meetings", "meetings", "اجتماع", "Meeting"),
    ("webinar", "webinars", "webinars", "ندوة", "Webinar"),
    ("certificate", "certs", "certs", "شهادة", "Certificate"),
    ("diploma", "diplomas", "diplomas", "دبلوم", "Diploma"),
    ("transcript", "transcripts", "transcripts", "كشف درجات", "Transcript"),
    ("enrollment", "enrollments", "enrollments", "تسجيل", "Enrollment"),
    ("classroom", "classrooms", "classrooms", "فصل", "Classroom"),
    ("homework", "homeworks", "homeworks", "واجب", "Homework"),
    ("grade", "grades", "grades", "درجة", "Grade"),
    ("rubric", "rubrics", "rubrics", "معيار", "Rubric"),
    ("announcement", "announcements", "announcements", "إعلان", "Announcement"),
    ("newsletter", "newsletters", "newsletters", "نشرة", "Newsletter"),
    ("blog", "blogs", "blogs", "مقال", "Blog"),
    ("page", "pages", "pages", "صفحة", "Page"),
    ("media", "media", "media", "وسائط", "Media"),
    ("gallery", "galleries", "galleries", "معرض", "Gallery"),
    ("album", "albums", "albums", "ألبوم", "Album"),
    ("playlist", "playlists", "playlists", "قائمة تشغيل", "Playlist"),
    ("track2", "tracks", "tracks", "مقطع صوتي", "Track"),
    ("artist", "artists", "artists", "فنان", "Artist"),
    ("venue", "venues", "venues", "مكان", "Venue"),
    ("ticket2", "event_tickets", "event_tickets", "تذكرة فعالية", "Event ticket"),
    ("checkin2", "checkins", "checkins", "تسجيل حضور", "Check-in"),
    ("sponsor", "sponsors", "sponsors", "راعي", "Sponsor"),
    ("partner", "partners", "partners", "شريك", "Partner"),
    ("investor", "investors", "investors", "مستثمر", "Investor"),
    ("startup", "startups", "startups", "شركة ناشئة", "Startup"),
    ("pitch", "pitches", "pitches", "عرض", "Pitch"),
    ("grant2", "grants", "grants", "منحة", "Grant"),
    ("scholarship", "scholarships", "scholarships", "منحة دراسية", "Scholarship"),
    ("donation", "donations", "donations", "تبرع", "Donation"),
    ("ngo", "ngos", "ngos", "منظمة", "NGO"),
    ("volunteer", "volunteers", "volunteers", "متطوع", "Volunteer"),
    ("mission", "missions", "missions", "مهمة إنسانية", "Mission"),
    ("supply", "supplies", "supplies", "إمداد", "Supply"),
    ("warehouse2", "wh2", "wh2", "مخزن", "Warehouse unit"),
    ("bin", "bins", "bins", "صندوق", "Bin"),
    ("lot", "lots", "lots", "دفعة", "Lot"),
    ("serial", "serials", "serials", "رقم تسلسلي", "Serial"),
    ("batch", "batches", "batches", "دفعة إنتاج", "Batch"),
    ("recipe", "recipes", "recipes", "وصفة", "Recipe"),
    ("ingredient", "ingredients", "ingredients", "مكون", "Ingredient"),
    ("allergen", "allergens", "allergens", "مسبب حساسية", "Allergen"),
    ("nutrition", "nutrition", "nutrition", "تغذية", "Nutrition"),
    ("diet", "diets", "diets", "حمية", "Diet"),
    ("workout", "workouts", "workouts", "تمرين", "Workout"),
    ("exercise", "exercises", "exercises", "حركة", "Exercise"),
    ("set2", "sets", "sets", "مجموعة تمارين", "Set"),
    ("pr", "prs", "prs", "رقم شخصي", "Personal record"),
    ("coach", "coaches", "coaches", "مدرب", "Coach"),
    ("trainee", "trainees", "trainees", "متدرب", "Trainee"),
    ("program", "programs", "programs", "برنامج", "Program"),
    ("module", "modules", "modules", "وحدة", "Module"),
    ("unit", "units", "units", "وحدة قياس", "Unit"),
    ("measure", "measures", "measures", "قياس", "Measure"),
    ("sample", "samples", "samples", "عينة", "Sample"),
    ("lab", "labs", "labs", "مختبر", "Lab"),
    ("test2", "lab_tests", "lab_tests", "تحليل", "Lab test"),
    ("result", "results", "results", "نتيجة تحليل", "Result"),
    ("prescription", "prescriptions", "prescriptions", "وصفة طبية", "Prescription"),
    ("medicine", "medicines", "medicines", "دواء", "Medicine"),
    ("pharmacy", "pharmacies", "pharmacies", "صيدلية", "Pharmacy"),
    ("patient", "patients", "patients", "مريض", "Patient"),
    ("doctor2", "doctors", "doctors", "طبيب", "Doctor"),
    ("nurse", "nurses", "nurses", "ممرض", "Nurse"),
    ("ward", "wards", "wards", "جناح", "Ward"),
    ("bed", "beds", "beds", "سرير", "Bed"),
    ("triage", "triages", "triages", "فرز", "Triage"),
    ("vitals", "vitals", "vitals", "علامات حيوية", "Vitals"),
    ("insurance", "insurances", "insurances", "تأمين", "Insurance"),
    ("claim2", "claims", "claims", "مطالبة", "Claim"),
    ("policy2", "ins_policies", "ins_policies", "وثيقة تأمين", "Insurance policy"),
    ("premium", "premiums", "premiums", "قسط", "Premium"),
    ("coverage", "coverages", "coverages", "تغطية", "Coverage"),
    ("risk", "risks", "risks", "خطر", "Risk"),
    ("compliance2", "compliances", "compliances", "امتثال", "Compliance"),
    ("audit2", "audits", "audits", "مراجعة", "Audit"),
    ("finding", "findings", "findings", "ملاحظة مراجعة", "Finding"),
    ("control", "controls", "controls", "ضبط", "Control"),
    ("asset2", "it_assets", "it_assets", "أصل تقني", "IT asset"),
    ("ticket_it", "it_tickets", "it_tickets", "تذكرة تقنية", "IT ticket"),
    ("change", "changes", "changes", "تغيير", "Change"),
    ("release2", "releases", "releases", "إصدار", "Release"),
    ("deploy", "deploys", "deploys", "نشر", "Deploy"),
    ("env", "envs", "envs", "بيئة", "Environment"),
    ("secret", "secrets", "secrets", "سر", "Secret"),
    ("config2", "configs", "configs", "تهيئة", "Config entry"),
    ("flag", "flags", "flags", "علم", "Flag"),
    ("experiment", "experiments", "experiments", "تجربة", "Experiment"),
    ("variant", "variants", "variants", "متغير", "Variant"),
    ("funnel", "funnels", "funnels", "قمع", "Funnel"),
    ("cohort", "cohorts", "cohorts", "مجموعة", "Cohort"),
    ("segment", "segments", "segments", "شريحة", "Segment"),
    ("persona", "personas", "personas", "شخصية", "Persona"),
    ("journey", "journeys", "journeys", "رحلة", "Journey"),
    ("touch", "touches", "touches", "لمسة", "Touchpoint"),
    ("nps", "nps", "nps", "رضا", "NPS"),
    ("csat2", "csat2", "csat2", "تقييم خدمة", "CSAT"),
    ("ces", "ces", "ces", "جهد عميل", "CES"),
    ("feedback2", "feedbacks", "feedbacks", "ملاحظة", "Feedback"),
    ("idea", "ideas", "ideas", "فكرة", "Idea"),
    ("roadmap", "roadmaps", "roadmaps", "خارطة", "Roadmap"),
    ("feature2", "features2", "features2", "ميزة منتج", "Product feature"),
    ("bug", "bugs", "bugs", "خلل", "Bug"),
    ("issue", "issues", "issues", "مشكلة", "Issue"),
    ("pr2", "pulls", "pulls", "طلب دمج", "Pull request"),
    ("commit", "commits", "commits", "التزام", "Commit"),
    ("branch", "branches", "branches", "فرع", "Branch"),
    ("repo", "repos", "repos", "مستودع", "Repository"),
    ("wiki", "wikis", "wikis", "ويكي", "Wiki"),
    ("snippet", "snippets", "snippets", "مقتطف", "Snippet"),
    ("macro", "macros", "macros", "ماكرو", "Macro"),
    ("bot_cmd", "bot_cmds", "bot_cmds", "أمر بوت", "Bot command"),
    ("bot_flow", "bot_flows", "bot_flows", "تدفق بوت", "Bot flow"),
    ("bot_state", "bot_states", "bot_states", "حالة بوت", "Bot state"),
    ("bot_kb", "bot_kbs", "bot_kbs", "لوحة بوت", "Bot keyboard"),
    ("bot_msg", "bot_msgs", "bot_msgs", "رسالة بوت", "Bot message"),

    # ── Expansion wave to 20k: real operational domains (generic.act-backed) ──
    ("clinic2", "clinic_ops", "clinic_ops", "عيادة", "Clinic ops"),
    ("doctor", "doctors", "doctors", "طبيب", "Doctor"),
    ("patient", "patients", "patients", "مريض", "Patient"),
    ("rx", "prescriptions", "prescriptions", "روشتة", "Prescription"),
    ("lab", "labs", "labs", "معمل", "Lab"),
    ("pharma", "pharmacy_ops", "pharmacy_ops", "صيدلية", "Pharmacy ops"),
    ("insurance2", "ins_claims", "ins_claims", "تأمين", "Insurance claim"),
    ("hotel2", "hotels", "hotels", "فندق", "Hotel"),
    ("room", "rooms", "rooms", "غرفة", "Room"),
    ("flight", "flights", "flights", "رحلة جوية", "Flight"),
    ("tour2", "tours", "tours", "جولة", "Tour"),
    ("visa", "visas", "visas", "تأشيرة", "Visa"),
    ("car2", "cars", "cars", "سيارة", "Car"),
    ("rental2", "rentals", "rentals", "تأجير", "Rental"),
    ("garage", "garages", "garages", "ورشة", "Garage"),
    ("fuel", "fuel", "fuel", "وقود", "Fuel"),
    ("parking", "parking", "parking", "موقف", "Parking"),
    ("property2", "properties", "properties", "عقار", "Property"),
    ("lease", "leases", "leases", "عقد إيجار", "Lease"),
    ("tenant2", "tenants", "tenants", "مستأجر", "Tenant"),
    ("maintenance2", "maint_ops", "maint_ops", "صيانة", "Maintenance"),
    ("job2", "jobs_ops", "jobs_ops", "وظيفة", "Job ops"),
    ("applicant", "applicants", "applicants", "متقدم", "Applicant"),
    ("interview", "interviews", "interviews", "مقابلة", "Interview"),
    ("payroll2", "payroll_ops", "payroll_ops", "رواتب", "Payroll"),
    ("leave2", "leave_ops", "leave_ops", "إجازة", "Leave"),
    ("attendance2", "attendance_ops", "attendance_ops", "حضور", "Attendance"),
    ("shift", "shifts", "shifts", "وردية", "Shift"),
    ("restaurant2", "resto_ops", "resto_ops", "مطعم", "Restaurant ops"),
    ("menu2", "menus", "menus", "قائمة طعام", "Menu"),
    ("table2", "tables", "tables", "طاولة", "Table"),
    ("kitchen", "kitchen", "kitchen", "مطبخ", "Kitchen"),
    ("delivery2", "delivery_ops", "delivery_ops", "توصيل", "Delivery ops"),
    ("courier", "couriers", "couriers", "مندوب", "Courier"),
    ("route2", "routes", "routes", "مسار", "Route"),
    ("shipment2", "shipments_ops", "shipments_ops", "شحنة", "Shipment ops"),
    ("warehouse3", "warehouse_ops", "warehouse_ops", "مستودع", "Warehouse ops"),
    ("fleet", "fleet", "fleet", "أسطول", "Fleet"),
    ("school2", "schools", "schools", "مدرسة", "School"),
    ("class2", "classes", "classes", "فصل", "Class"),
    ("student2", "students", "students", "طالب", "Student"),
    ("grade", "grades", "grades", "درجة", "Grade"),
    ("homework2", "homeworks", "homeworks", "واجب", "Homework"),
    ("exam", "exams", "exams", "اختبار", "Exam"),
    ("library2", "libraries", "libraries", "مكتبة", "Library"),
    ("book2", "books", "books", "كتاب", "Book"),
    ("gym2", "gym_ops", "gym_ops", "جيم", "Gym ops"),
    ("trainer", "trainers", "trainers", "مدرب", "Trainer"),
    ("session2", "sessions", "sessions", "حصة", "Session"),
    ("membership2", "memberships", "memberships", "عضوية", "Membership"),
    ("salon", "salons", "salons", "صالون", "Salon"),
    ("appointment2", "appointments", "appointments", "موعد", "Appointment"),
    ("legal2", "legal_ops", "legal_ops", "قانوني", "Legal ops"),
    ("case2", "cases", "cases", "قضية", "Case"),
    ("contract2", "contracts", "contracts", "عقد", "Contract"),
    ("court", "courts", "courts", "محكمة", "Court"),
    ("media2", "media_ops", "media_ops", "إعلام", "Media ops"),
    ("article2", "articles", "articles", "مقال", "Article"),
    ("podcast2", "podcasts", "podcasts", "بودكاست", "Podcast"),
    ("episode", "episodes", "episodes", "حلقة", "Episode"),
    ("stream", "streams", "streams", "بث", "Stream"),
    ("ad2", "ads_ops", "ads_ops", "إعلان", "Ad ops"),
    ("creative", "creatives", "creatives", "إبداعي", "Creative"),
    ("budget2", "budgets", "budgets", "ميزانية", "Budget"),
    ("invoice3", "invoices_ops", "invoices_ops", "فاتورة", "Invoice ops"),
    ("tax2", "tax_ops", "tax_ops", "ضريبة", "Tax ops"),
    ("expense", "expenses", "expenses", "مصروف", "Expense"),
    ("refund3", "refunds_ops", "refunds_ops", "استرجاع", "Refund ops"),
    ("dispute2", "disputes", "disputes", "نزاع", "Dispute"),
    ("kyc", "kyc_ops", "kyc_ops", "تحقق هوية", "KYC"),
    ("aml", "aml_ops", "aml_ops", "مكافحة غسل", "AML"),
    ("loan", "loans", "loans", "قرض", "Loan"),
    ("card2", "cards", "cards", "بطاقة", "Card"),
    ("pos", "pos_ops", "pos_ops", "نقطة بيع", "POS"),
    ("branch", "branches", "branches", "فرع", "Branch"),
    ("franchise", "franchises", "franchises", "امتياز", "Franchise"),
    ("supplier2", "suppliers", "suppliers", "مورد", "Supplier"),
    ("purchase", "purchases", "purchases", "مشتريات", "Purchase"),
    ("rfq", "rfqs", "rfqs", "طلب عرض سعر", "RFQ"),
    ("po", "purchase_orders", "purchase_orders", "أمر شراء", "Purchase order"),
    ("asset2", "assets", "assets", "أصل", "Asset"),
    ("license2", "licenses", "licenses", "رخصة", "License"),
    ("compliance2", "compliance_ops", "compliance_ops", "امتثال", "Compliance ops"),
    ("audit2", "audits", "audits", "تدقيق", "Audit"),
    ("risk", "risks", "risks", "مخاطر", "Risk"),
    ("incident2", "incidents_ops", "incidents_ops", "حادث", "Incident ops"),
    ("sla2", "slas", "slas", "اتفاقية مستوى", "SLA"),
    ("kb2", "knowledge", "knowledge", "معرفة", "Knowledge"),
    ("macro", "macros", "macros", "ماكرو", "Macro"),
    ("canned", "canned_replies", "canned_replies", "رد جاهز", "Canned reply"),
    ("survey2", "surveys", "surveys", "استبيان", "Survey"),
    ("nps", "nps_ops", "nps_ops", "صافي الترويج", "NPS"),
    ("segment2", "segments_ops", "segments_ops", "شريحة", "Segment ops"),
    ("journey", "journeys", "journeys", "رحلة عميل", "Journey"),
    ("automation2", "automations", "automations", "أتمتة", "Automation"),
    ("webhook2", "webhooks_ops", "webhooks_ops", "ويب هوك", "Webhook ops"),
    ("api2", "api_ops", "api_ops", "واجهة برمجة", "API ops"),
    ("tenant3", "tenants_ops", "tenants_ops", "مستأجر نظام", "Tenant ops"),
    ("workspace", "workspaces", "workspaces", "مساحة عمل", "Workspace"),
    ("project2", "projects", "projects", "مشروع", "Project"),
    ("sprint", "sprints", "sprints", "سبرنت", "Sprint"),
    ("issue2", "issues", "issues", "مشكلة", "Issue"),
    ("bug", "bugs", "bugs", "خلل", "Bug"),
    ("release2", "releases", "releases", "إصدار", "Release"),
    ("env2", "environments", "environments", "بيئة", "Environment"),
    ("monitor", "monitors", "monitors", "مراقبة", "Monitor"),
    ("alert2", "alerts", "alerts", "تنبيه", "Alert"),
    ("backup2", "backups", "backups", "نسخة احتياطية", "Backup"),
    ("restore2", "restores", "restores", "استعادة", "Restore ops"),


    # ── Complex systems wave → 30k (SaaS / marketplace / logistics / light finance) ──
    ("saas", "saas_core", "saas", "ساس", "SaaS"),
    ("seat", "saas_seats", "saas", "مقعد", "Seat"),
    ("plan3", "saas_plans", "saas", "خطة ساس", "SaaS plan"),
    ("billing2", "saas_billing", "saas", "فوترة ساس", "SaaS billing"),
    ("meter", "saas_meters", "saas", "عداد استخدام", "Usage meter"),
    ("quota", "saas_quotas", "saas", "حصة", "Quota"),
    ("sso", "saas_sso", "saas", "دخول موحد", "SSO"),
    ("saml", "saas_saml", "saas", "سامال", "SAML"),
    ("scim", "saas_scim", "saas", "سكيم", "SCIM"),
    ("entitlement", "saas_entitlements", "saas", "استحقاق", "Entitlement"),
    ("subscription2", "saas_subs", "saas", "اشتراك ساس", "SaaS subscription"),
    ("trial2", "saas_trials", "saas", "تجربة ساس", "SaaS trial"),
    ("addon2", "saas_addons", "saas", "إضافة ساس", "SaaS add-on"),
    ("workspace2", "saas_workspaces", "saas", "مساحة ساس", "SaaS workspace"),
    ("org", "saas_orgs", "saas", "منظمة", "Organization"),
    ("team2", "saas_teams", "saas", "فريق ساس", "SaaS team"),
    ("rbac", "saas_rbac", "saas", "صلاحيات", "RBAC"),
    ("audit3", "saas_audit", "saas", "تدقيق ساس", "SaaS audit"),
    ("flag2", "saas_flags", "saas", "أعلام ميزات", "Feature flags"),
    ("env3", "saas_envs", "saas", "بيئة ساس", "SaaS environment"),
    ("deploy2", "saas_deploys", "saas", "نشر", "Deploy"),
    ("pipeline2", "saas_pipelines", "saas", "خط نشر", "Pipeline"),
    ("webhook3", "saas_webhooks", "saas", "ويب هوك ساس", "SaaS webhook"),
    ("apikey", "saas_apikeys", "saas", "مفتاح API", "API key"),
    ("oauth2", "saas_oauth", "saas", "أواث", "OAuth"),
    ("mkt", "mkt_core", "marketplace", "سوق", "Marketplace"),
    ("listing2", "mkt_listings", "marketplace", "إعلان سوق", "Marketplace listing"),
    ("vendor2", "mkt_vendors", "marketplace", "بائع سوق", "Marketplace vendor"),
    ("buyer", "mkt_buyers", "marketplace", "مشتري", "Buyer"),
    ("offer2", "mkt_offers", "marketplace", "عرض سوق", "Marketplace offer"),
    ("bid2", "mkt_bids", "marketplace", "مزايدة سوق", "Marketplace bid"),
    ("escrow", "mkt_escrow", "marketplace", "ضمان", "Escrow"),
    ("payout2", "mkt_payouts", "marketplace", "صرف بائع", "Vendor payout"),
    ("commission2", "mkt_commissions", "marketplace", "عمولة سوق", "Marketplace commission"),
    ("catalog2", "mkt_catalog", "marketplace", "كتالوج سوق", "Marketplace catalog"),
    ("storefront", "mkt_storefronts", "marketplace", "واجهة متجر", "Storefront"),
    ("marketplace2", "mkt_hub", "marketplace", "مركز سوق", "Marketplace hub"),
    ("auction3", "mkt_auctions", "marketplace", "مزاد سوق", "Marketplace auction"),
    ("rfq2", "mkt_rfqs", "marketplace", "طلب تسعير", "RFQ"),
    ("quote2", "mkt_quotes", "marketplace", "عرض سعر", "Quote"),
    ("dispute3", "mkt_disputes", "marketplace", "نزاع سوق", "Marketplace dispute"),
    ("review3", "mkt_reviews", "marketplace", "تقييم سوق", "Marketplace review"),
    ("rating2", "mkt_ratings", "marketplace", "تقييم رقمي", "Rating"),
    ("logi", "logi_core", "logistics", "لوجستيات", "Logistics"),
    ("ship4", "logi_shipments", "logistics", "شحنة لوجستية", "Logistics shipment"),
    ("fleet2", "logi_fleet", "logistics", "أسطول", "Fleet"),
    ("route3", "logi_routes", "logistics", "مسار لوجستي", "Logistics route"),
    ("hub2", "logi_hubs", "logistics", "مركز توزيع", "Distribution hub"),
    ("dock2", "logi_docks", "logistics", "رصيف", "Dock"),
    ("warehouse4", "logi_warehouses", "logistics", "مستودع لوجستي", "Logistics warehouse"),
    ("courier2", "logi_couriers", "logistics", "مندوب لوجستي", "Logistics courier"),
    ("manifest", "logi_manifests", "logistics", "بيان شحن", "Manifest"),
    ("lane", "logi_lanes", "logistics", "مسار ثابت", "Lane"),
    ("yard2", "logi_yards", "logistics", "ساحة", "Yard"),
    ("container", "logi_containers", "logistics", "حاوية", "Container"),
    ("pallet", "logi_pallets", "logistics", "باليت", "Pallet"),
    ("lastmile", "logi_lastmile", "logistics", "الميل الأخير", "Last mile"),
    ("crossdock", "logi_crossdock", "logistics", "عبور مستودع", "Cross-dock"),
    ("pod2", "logi_pod", "logistics", "إثبات تسليم", "POD"),
    ("eta2", "logi_eta", "logistics", "وقت وصول", "ETA"),
    ("load2", "logi_loads", "logistics", "حمولة", "Load"),
    ("trip", "logi_trips", "logistics", "رحلة نقل", "Trip"),
    ("fin", "fin_core", "finance", "مالية", "Finance"),
    ("ledger2", "fin_ledger", "finance", "دفتر أستاذ", "Ledger"),
    ("journal", "fin_journal", "finance", "قيد يومية", "Journal"),
    ("payout3", "fin_payouts", "finance", "صرف مالي", "Finance payout"),
    ("settle2", "fin_settlement", "finance", "تسوية مالية", "Settlement"),
    ("recon", "fin_recon", "finance", "مطابقة", "Reconciliation"),
    ("treasury", "fin_treasury", "finance", "خزينة", "Treasury"),
    ("fx", "fin_fx", "finance", "صرف عملات", "FX"),
    ("card3", "fin_cards", "finance", "بطاقة مالية", "Finance card"),
    ("wallet3", "fin_wallets", "finance", "محفظة مالية", "Finance wallet"),
    ("loan2", "fin_loans", "finance", "قرض", "Loan"),
    ("credit2", "fin_credit", "finance", "ائتمان", "Credit"),
    ("limit2", "fin_limits", "finance", "حد مالي", "Finance limit"),
    ("kyc2", "fin_kyc", "finance", "تحقق هوية مالي", "Finance KYC"),
    ("aml2", "fin_aml", "finance", "مكافحة غسل", "AML"),
    ("invoice4", "fin_invoices", "finance", "فاتورة مالية", "Finance invoice"),
    ("receivable", "fin_ar", "finance", "ذمم مدينة", "Receivable"),
    ("payable", "fin_ap", "finance", "ذمم دائنة", "Payable"),
    ("tax3", "fin_tax", "finance", "ضريبة مالية", "Finance tax"),
    ("fee2", "fin_fees", "finance", "رسوم", "Fee"),
    ("charge2", "fin_charges", "finance", "رسوم مدينة", "Charge"),
]

# Domain-specific action sets: which vocab to apply
_SETS = {
    "default": CRUD + WORKFLOW,
    "commerce": CRUD + COMMERCE + WORKFLOW,
    "social": CRUD + SOCIAL,
    "game": CRUD + GAMING,
    "admin": CRUD + ADMIN + WORKFLOW,
}

_COMMERCE_PREFIXES = {
    "inv", "sku", "ord", "pay", "sub", "coup", "aff", "pts", "wal", "gift",
    "ship", "auc", "bid", "store", "vendor", "cust", "invoice2", "promo",
    "flash", "bundle", "addon", "plan2", "refund2", "return2", "exchange",
    "payout", "settlement", "chargeback", "premium", "donation",
}
_SOCIAL_PREFIXES = {
    "post", "cmt", "feed", "grp", "chn", "msg", "follow", "blog", "gallery",
    "album", "playlist", "artist", "sponsor", "partner",
}
_GAME_PREFIXES = {
    "badge2", "quest2", "ach", "tier", "pts", "gym", "workout", "exercise",
    "set2", "pr", "habit", "goal",
}
_ADMIN_PREFIXES = {
    "staff", "role", "perm", "log", "metric", "report", "hook", "api",
    "config2", "flag", "secret", "env", "deploy", "audit2", "compliance2",
}



_SAAS_PREFIXES = {
    "saas", "tenant3", "workspace", "seat", "plan3", "billing2", "meter",
    "quota", "sso", "saml", "scim", "entitlement", "subscription2", "trial2",
    "addon2", "workspace2", "org", "team2", "rbac", "audit3", "flag2",
    "env3", "deploy2", "pipeline2", "webhook3", "apikey", "oauth2",
}
_MARKETPLACE_PREFIXES = {
    "mkt", "listing2", "vendor2", "buyer", "offer2", "bid2", "escrow",
    "payout2", "commission2", "catalog2", "storefront", "marketplace2",
    "auction3", "rfq2", "quote2", "dispute3", "review3", "rating2",
}
_LOGISTICS_PREFIXES = {
    "logi", "ship4", "fleet2", "route3", "hub2", "dock2", "warehouse4",
    "courier2", "manifest", "lane", "yard2", "container", "pallet",
    "lastmile", "crossdock", "pod2", "eta2", "load2", "trip",
}
_FINANCE_PREFIXES = {
    "fin", "ledger2", "journal", "payout3", "settle2", "recon", "treasury",
    "fx", "card3", "wallet3", "loan2", "credit2", "limit2", "kyc2", "aml2",
    "invoice4", "receivable", "payable", "tax3", "fee2", "charge2",
}

def _action_set(prefix: str) -> tuple:
    if prefix in _SAAS_PREFIXES:
        return COMPLEX_SAAS
    if prefix in _MARKETPLACE_PREFIXES:
        return COMPLEX_MARKETPLACE
    if prefix in _LOGISTICS_PREFIXES:
        return COMPLEX_LOGISTICS
    if prefix in _FINANCE_PREFIXES:
        return COMPLEX_FINANCE
    if prefix in _COMMERCE_PREFIXES:
        return _SETS["commerce"]
    if prefix in _SOCIAL_PREFIXES:
        return _SETS["social"]
    if prefix in _GAME_PREFIXES:
        return _SETS["game"]
    if prefix in _ADMIN_PREFIXES:
        return _SETS["admin"]
    return _SETS["default"]


def _actor_for(action: str) -> str:
    if action in {
        "approve", "reject", "assign", "escalate", "ban", "unban", "role_set",
        "broadcast", "config", "metrics", "backup", "feature_flag", "import_data",
        "export", "audit", "audit_log", "health", "restore_backup", "toggle",
    }:
        return "admin"
    return "user"


def expand_scale_capabilities(*, target: int = 30000) -> int:
    """Generate capabilities until CAPABILITIES reaches target size.

    Coverage is non-fake: every key maps to (service, method) executed by
    generic.act / market services (list/create/update/delete/search/...).
    """
    before = len(CAPABILITIES)
    batch: list[Capability] = []

    def flush() -> None:
        nonlocal batch
        if batch:
            _add(*batch)
            batch = []

    for prefix, service, cat, ar_name, en_name in VERTICALS:
        for action, ar_act, en_act in _action_set(prefix):
            key = f"{prefix}_{action}"
            if key in CAPABILITIES:
                continue
            actor = _actor_for(action)
            batch.append(
                _c(
                    key,
                    service,
                    action,
                    f"{ar_act} {ar_name}",
                    f"{en_act} {en_name}",
                    actor,
                    cat=cat,
                )
            )
            if len(CAPABILITIES) + len(batch) >= target:
                flush()
                return len(CAPABILITIES) - before
        if len(batch) >= 500:
            flush()

    flush()

    fill_actions = (
        "list", "view", "create", "update", "delete", "search", "filter",
        "export", "archive", "restore", "share", "assign", "approve",
        "reject", "status", "stats", "history", "track", "schedule",
    )
    fill_domains = (
        ("ops", "ops_desk", "ops"),
        ("hq", "hq_ops", "ops"),
        ("unit", "units", "ops"),
        ("desk", "service_desk", "support"),
        ("queue", "queues", "support"),
        ("agent", "agents", "support"),
        ("client", "clients", "crm"),
        ("account", "accounts", "crm"),
        ("opportunity", "opportunities", "crm"),
        ("sku2", "sku_ops", "commerce"),
        ("price", "pricing", "commerce"),
        ("promo2", "promotions", "commerce"),
        ("stock2", "stock_ops", "commerce"),
        ("ship3", "shipping_ops", "logistics"),
        ("dock", "docks", "logistics"),
        ("hub", "hubs", "logistics"),
        ("yard", "yards", "logistics"),
        ("crew", "crews", "hr"),
        ("roster", "rosters", "hr"),
        ("skill", "skills", "hr"),
        ("site", "sites", "facilities"),
        ("floor", "floors", "facilities"),
        ("device", "devices", "iot"),
        ("sensor", "sensors", "iot"),
        ("metric2", "metrics_ops", "analytics"),
        ("report2", "reports_ops", "analytics"),
        ("board2", "boards", "analytics"),
        # complex systems fill (real methods only)
        ("saasx", "saas_ops", "saas"),
        ("mktx", "mkt_ops", "marketplace"),
        ("logix", "logi_ops", "logistics"),
        ("finx", "fin_ops", "finance"),
        ("tenantx", "tenant_ops", "saas"),
        ("vendorx", "vendor_ops", "marketplace"),
        ("fleetx", "fleet_ops", "logistics"),
        ("ledgerx", "ledger_ops", "finance"),
        ("escrowx", "escrow_ops", "marketplace"),
        ("routex", "route_ops", "logistics"),
        ("wallettx", "wallet_ops", "finance"),
        ("quotax", "quota_ops", "saas"),
    )
    for i in range(1, 1200):
        if len(CAPABILITIES) >= target:
            break
        for prefix, svc, cat in fill_domains:
            if len(CAPABILITIES) >= target:
                break
            for action in fill_actions:
                if len(CAPABILITIES) >= target:
                    break
                key = f"{prefix}_{i:03d}_{action}"
                if key in CAPABILITIES:
                    continue
                batch.append(
                    _c(
                        key,
                        svc,
                        action,
                        f"{action} {prefix} {i}",
                        f"{action} {prefix} {i}",
                        cat=cat,
                    )
                )
                if len(batch) >= 400:
                    flush()
    flush()
    return len(CAPABILITIES) - before



# Deliberately no import-time expansion. The primary registry loads this module
# only through load_scale_capabilities() when a caller explicitly requests it.
_ADDED = 0

__all__ = ["expand_scale_capabilities", "VERTICALS", "_ADDED"]
