"""Emit service modules for generated bots (split package)."""
from __future__ import annotations

from ..schema import BotSpec

def _emit_lean_generic_service() -> str:
    """Working generic.act store — never a dead stub. Used when fat runtime is not selected."""
    return (
        '"""Lean generic service — sqlite act() store for any entity/method."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            'CREATE TABLE IF NOT EXISTS generic_kv ('\n"
        "            'id INTEGER PRIMARY KEY AUTOINCREMENT, '\n"
        "            'user_id INTEGER NOT NULL DEFAULT 0, '\n"
        "            'entity TEXT NOT NULL, '\n"
        "            'method TEXT NOT NULL DEFAULT \\'\\', '\n"
        "            'body TEXT NOT NULL, '\n"
        "            'status TEXT NOT NULL DEFAULT \\'open\\', '\n"
        "            'created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'\n"
        "        )\n"
        "        conn.commit()\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    ent = (entity or 'item').strip().lower() or 'item'\n"
        "    meth = (method or '').strip().lower()\n"
        "    body = (text or '').strip()[:500]\n"
        "    uid = int(user_id)\n\n"
        "    # create / set / add / book / open\n"
        "    if meth in {\n"
        "        'add', 'set', 'create', 'book', 'book_slot', 'open', 'capture',\n"
        "        'set_reminder', 'lead_capture', 'submit', 'start', 'enroll', 'rsvp',\n"
        "    } or meth.endswith('_add') or meth.endswith('_create') or meth.endswith('_set'):\n"
        "        with connect() as conn:\n"
        "            cur = conn.execute(\n"
        "                'INSERT INTO generic_kv (user_id, entity, method, body, status) VALUES (?, ?, ?, ?, ?)',\n"
        "                (uid, ent, meth, body or ent, 'open'),\n"
        "            )\n"
        "            conn.commit()\n"
        "            return f'تم التسجيل #{int(cur.lastrowid)}'\n\n"
        "    # list / my / status\n"
        "    if meth in {\n"
        "        'list', 'list_open', 'my', 'my_appointments', 'list_bookings', 'list_reminders',\n"
        "        'lead_list', 'status', 'view', 'overview',\n"
        "    } or meth.startswith('list') or meth.startswith('my_'):\n"
        "        with connect() as conn:\n"
        "            rows = conn.execute(\n"
        "                \"SELECT id, body, status FROM generic_kv \"\n"
        "                \"WHERE user_id = ? AND entity = ? AND status = 'open' ORDER BY id DESC LIMIT 30\",\n"
        "                (uid, ent),\n"
        "            ).fetchall()\n"
        "        if not rows:\n"
        "            return 'لا توجد عناصر'\n"
        "        return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows)\n\n"
        "    # cancel / close / delete / clear\n"
        "    if meth in {'cancel', 'cancel_booking', 'close', 'delete', 'clear', 'clear_reminders'} or meth.startswith('cancel'):\n"
        "        parts = body.split()\n"
        "        try:\n"
        "            iid = int(parts[0]) if parts else 0\n"
        "        except ValueError:\n"
        "            iid = 0\n"
        "        with connect() as conn:\n"
        "            if iid:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE generic_kv SET status = 'closed' WHERE id = ? AND user_id = ?\",\n"
        "                    (iid, uid),\n"
        "                )\n"
        "            else:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE generic_kv SET status = 'closed' WHERE user_id = ? AND entity = ? AND status = 'open'\",\n"
        "                    (uid, ent),\n"
        "                )\n"
        "            conn.commit()\n"
        "            return f'تم الإغلاق ({int(cur.rowcount)})'\n\n"
        "    # default: store note under entity\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO generic_kv (user_id, entity, method, body, status) VALUES (?, ?, ?, ?, ?)',\n"
        "            (uid, ent, meth or 'note', body or meth or ent, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم الحفظ #{int(cur.lastrowid)}'\n\n\n"
        "def list_due_reminders(now_ts=None, limit: int = 50):\n"
        "    return []\n\n\n"
        "def mark_reminder_fired(reminder_id: int) -> bool:\n"
        "    return False\n"
    )



def _emit_lean_named_service(name: str) -> str:
    """Working named service module that delegates to lean patterns via local sqlite."""
    safe = "".join(ch for ch in (name or "svc") if ch.isalnum() or ch == "_") or "svc"
    return (
        f'"""Auto service `{safe}` — working sqlite-backed handlers."""\n'
        "from __future__ import annotations\n\n"
        "from app.db import connect, init_db\n\n"
        f"_ENTITY = {safe!r}\n\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            'CREATE TABLE IF NOT EXISTS entity_kv ('\n"
        "            'id INTEGER PRIMARY KEY AUTOINCREMENT, '\n"
        "            'user_id INTEGER NOT NULL DEFAULT 0, '\n"
        "            'entity TEXT NOT NULL, '\n"
        "            'body TEXT NOT NULL, '\n"
        "            'status TEXT NOT NULL DEFAULT \\'open\\', '\n"
        "            'created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'\n"
        "        )\n"
        "        conn.commit()\n\n\n"
        "def act(entity: str, method: str, user_id: int, text: str = '') -> str:\n"
        "    ensure()\n"
        "    ent = (entity or _ENTITY).strip().lower() or _ENTITY\n"
        "    meth = (method or '').strip().lower()\n"
        "    body = (text or '').strip()[:500]\n"
        "    uid = int(user_id)\n"
        "    if meth in {'list', 'my', 'view', 'status'} or meth.startswith('list') or meth.startswith('my_'):\n"
        "        with connect() as conn:\n"
        "            rows = conn.execute(\n"
        "                \"SELECT id, body FROM entity_kv WHERE user_id = ? AND entity = ? AND status = 'open' ORDER BY id DESC LIMIT 30\",\n"
        "                (uid, ent),\n"
        "            ).fetchall()\n"
        "        return '\\n'.join(f\"#{r['id']} {r['body']}\" for r in rows) if rows else 'لا توجد عناصر'\n"
        "    if meth in {'cancel', 'close', 'delete', 'clear'} or meth.startswith('cancel'):\n"
        "        parts = body.split()\n"
        "        try:\n"
        "            iid = int(parts[0]) if parts else 0\n"
        "        except ValueError:\n"
        "            iid = 0\n"
        "        with connect() as conn:\n"
        "            if iid:\n"
        "                cur = conn.execute(\"UPDATE entity_kv SET status='closed' WHERE id=? AND user_id=?\", (iid, uid))\n"
        "            else:\n"
        "                cur = conn.execute(\n"
        "                    \"UPDATE entity_kv SET status='closed' WHERE user_id=? AND entity=? AND status='open'\",\n"
        "                    (uid, ent),\n"
        "                )\n"
        "            conn.commit()\n"
        "            return f'تم الإغلاق ({int(cur.rowcount)})'\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            'INSERT INTO entity_kv (user_id, entity, body, status) VALUES (?, ?, ?, ?)',\n"
        "            (uid, ent, body or meth or ent, 'open'),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return f'تم الحفظ #{int(cur.lastrowid)}'\n\n\n"
        "def __getattr__(item: str):\n"
        "    def _call(*args, **kwargs):\n"
        "        uid = 0\n"
        "        text = ''\n"
        "        if args:\n"
        "            uid = int(args[0]) if str(args[0]).lstrip('-').isdigit() else 0\n"
        "            if len(args) > 1:\n"
        "                text = str(args[1])\n"
        "        return act(_ENTITY, item, uid, text)\n"
        "    return _call\n"
    )



