"""Emit service modules for generated bots (split package)."""
from __future__ import annotations

from ..schema import BotSpec

def _emit_pubg() -> str:
    """PUBG / group gaming: players, teams, matches, points, tournaments."""
    return (
        "\"\"\"PUBG service — players, teams, matches, points, tournaments (per chat).\"\"\"\n"
        "from __future__ import annotations\n"
        "\n"
        "import time\n"
        "from app.db import connect, init_db\n"
        "\n"
        "\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_players (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"ign TEXT NOT NULL DEFAULT '', team TEXT NOT NULL DEFAULT '', \"\n"
        "            \"points INTEGER NOT NULL DEFAULT 0, matches INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"wins INTEGER NOT NULL DEFAULT 0, kills INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_matches (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"note TEXT NOT NULL DEFAULT '', points_awarded INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, created_by INTEGER NOT NULL DEFAULT 0)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS pubg_tournaments (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', \"\n"
        "            \"created_at INTEGER NOT NULL DEFAULT 0, created_by INTEGER NOT NULL DEFAULT 0)\"\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def register_player(chat_id: int, user_id: int, ign: str = \"\") -> str:\n"
        "    ensure()\n"
        "    ign = (ign or f\"player_{user_id}\")[:64]\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO pubg_players (chat_id, user_id, ign, created_at) VALUES (?, ?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET ign = excluded.ign\",\n"
        "            (int(chat_id), int(user_id), ign, int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تم تسجيل اللاعب: {ign}\"\n"
        "\n"
        "\n"
        "def list_players(chat_id: int, limit: int = 30) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT user_id, ign, team, points, matches, wins, kills FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? ORDER BY points DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 50))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا يوجد لاعبون مسجلون\"\n"
        "    lines = [f\"• {r['ign']} (uid={r['user_id']}) team={r['team'] or '-'} pts={r['points']} W={r['wins']} K={r['kills']}\" for r in rows]\n"
        "    return \"قائمة اللاعبين:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "\n"
        "def set_team(chat_id: int, user_id: int, team: str) -> str:\n"
        "    ensure()\n"
        "    team = (team or \"\")[:32]\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT user_id FROM pubg_players WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        if not row:\n"
        "            conn.execute(\n"
        "                \"INSERT INTO pubg_players (chat_id, user_id, ign, team, created_at) VALUES (?, ?, ?, ?, ?)\",\n"
        "                (int(chat_id), int(user_id), f\"player_{user_id}\", team, int(time.time())),\n"
        "            )\n"
        "        else:\n"
        "            conn.execute(\n"
        "                \"UPDATE pubg_players SET team = ? WHERE chat_id = ? AND user_id = ?\",\n"
        "                (team, int(chat_id), int(user_id)),\n"
        "            )\n"
        "        conn.commit()\n"
        "    return f\"فريق {user_id}: {team or '-'}\"\n"
        "\n"
        "\n"
        "def list_teams(chat_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT team, COUNT(*) AS n, SUM(points) AS pts FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? AND team != '' GROUP BY team ORDER BY pts DESC\",\n"
        "            (int(chat_id),),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا توجد فرق\"\n"
        "    return \"الفرق:\\n\" + \"\\n\".join(f\"• {r['team']}: members={r['n']} pts={r['pts']}\" for r in rows)\n"
        "\n"
        "\n"
        "def record_match(chat_id: int, admin_id: int, note: str = \"\", points: int = 10, winner_id: int = 0, kills: int = 0) -> str:\n"
        "    ensure()\n"
        "    points = max(0, min(int(points), 1000))\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO pubg_matches (chat_id, note, points_awarded, created_at, created_by) VALUES (?, ?, ?, ?, ?)\",\n"
        "            (int(chat_id), (note or \"\")[:200], points, int(time.time()), int(admin_id)),\n"
        "        )\n"
        "        if winner_id:\n"
        "            conn.execute(\n"
        "                \"INSERT INTO pubg_players (chat_id, user_id, ign, points, matches, wins, kills, created_at) \"\n"
        "                \"VALUES (?, ?, ?, ?, 1, 1, ?, ?) \"\n"
        "                \"ON CONFLICT(chat_id, user_id) DO UPDATE SET \"\n"
        "                \"points = points + excluded.points, matches = matches + 1, wins = wins + 1, kills = kills + excluded.kills\",\n"
        "                (int(chat_id), int(winner_id), f\"player_{winner_id}\", points, int(kills), int(time.time())),\n"
        "            )\n"
        "        conn.commit()\n"
        "    return f\"سُجلت مباراة (+{points} نقطة)\" + (f\" للفائز {winner_id}\" if winner_id else \"\")\n"
        "\n"
        "\n"
        "def top_players(chat_id: int, limit: int = 10) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT ign, user_id, points, wins, kills FROM pubg_players \"\n"
        "            \"WHERE chat_id = ? ORDER BY points DESC, wins DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 25))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا يوجد ترتيب بعد\"\n"
        "    lines = [f\"{i+1}. {r['ign']} — {r['points']} pts | W={r['wins']} K={r['kills']}\" for i, r in enumerate(rows)]\n"
        "    return \"Top Players:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "\n"
        "def player_stats(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT * FROM pubg_players WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    if not row:\n"
        "        return \"اللاعب غير مسجل — استخدم /pubg_register\"\n"
        "    return (\n"
        "        f\"إحصائيات {row['ign']}:\\n\"\n"
        "        f\"النقاط: {row['points']}\\nالمباريات: {row['matches']}\\n\"\n"
        "        f\"الانتصارات: {row['wins']}\\nالقتل: {row['kills']}\\nالفريق: {row['team'] or '-'}\"\n"
        "    )\n"
        "\n"
        "\n"
        "def create_tournament(chat_id: int, admin_id: int, title: str) -> str:\n"
        "    ensure()\n"
        "    title = (title or \"Tournament\").strip()[:80]\n"
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        "            \"INSERT INTO pubg_tournaments (chat_id, title, status, created_at, created_by) VALUES (?, ?, 'open', ?, ?)\",\n"
        "            (int(chat_id), title, int(time.time()), int(admin_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "        tid = int(cur.lastrowid)\n"
        "    return f\"بطولة #{tid}: {title} (مفتوحة)\"\n"
    )


