"""Emit service modules for generated bots (split package)."""
from __future__ import annotations

from ..schema import BotSpec

def _emit_security() -> str:
    return (
        '"""Defensive security ops — reports, awareness, and passive domain checks.\n'
        "\n"
        "No offensive / exploit tooling. Network helpers use stdlib only.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "import re\n"
        "import socket\n"
        "import ssl\n"
        "from urllib.parse import urlparse\n"
        "from urllib.request import Request, urlopen\n\n"
        "from app.db import connect, init_db\n\n"
        "CHECKLIST = (\n"
        '    "1) لا تشارك كلمات المرور أو رموز التحقق\\n"\n'
        '    "2) راجع الروابط قبل الفتح\\n"\n'
        '    "3) فعّل التحقق بخطوتين\\n"\n'
        '    "4) بلّغ فورًا عن أي رسالة مشبوهة\\n"\n'
        '    "5) حدّث التطبيقات باستمرار"\n'
        ")\n\n"
        "TIPS = (\n"
        '    "• استخدم كلمات مرور فريدة لكل خدمة\\n"\n'
        '    "• فعّل 2FA / مفاتيح المرور\\n"\n'
        '    "• لا تفتح مرفقات غير متوقعة\\n"\n'
        '    "• راجع صلاحيات التطبيقات دوريًا"\n'
        ")\n\n"
        "PASSWORD_TIPS = (\n"
        '    "• 12+ حرف مع تنوع (أحرف/أرقام/رموز)\\n"\n'
        '    "• لا تعِد استخدام نفس كلمة المرور\\n"\n'
        '    "• مدير كلمات مرور موثوق أفضل من الذاكرة\\n"\n'
        '    "• غيّر فوريًا بعد أي تسريب معروف"\n'
        ")\n\n"
        "_HOST_RE = re.compile(r\"^[a-zA-Z0-9](?:[a-zA-Z0-9\\-\\.]{0,251}[a-zA-Z0-9])?$\")\n\n"
        "def ensure() -> None:\n"
        "    init_db()\n\n"
        "def _clean_host(raw: str) -> str:\n"
        "    t = (raw or '').strip().lower()\n"
        "    if '://' in t:\n"
        "        t = urlparse(t).hostname or t\n"
        "    t = t.split('/')[0].split('?')[0].strip().strip('.')\n"
        "    if t.startswith('www.'):\n"
        "        t = t[4:]\n"
        "    if not t or not _HOST_RE.match(t) or len(t) > 253:\n"
        "        return ''\n"
        "    return t\n\n"
        "def report(user_id: int, kind: str, body: str) -> int:\n"
        "    ensure()\n"
        '    kind = (kind or "incident").strip()[:40]\n'
        '    body = (body or "").strip() or "—"\n'
        "    with connect() as conn:\n"
        "        cur = conn.execute(\n"
        '            "INSERT INTO security_reports (user_id, kind, body, status) VALUES (?, ?, ?, \'open\')",\n'
        "            (user_id, kind, body[:2000]),\n"
        "        )\n"
        "        conn.commit()\n"
        "        return int(cur.lastrowid)\n\n"
        "def list_reports(only_open: bool = True, limit: int = 20) -> list[dict]:\n"
        "    ensure()\n"
        '    q = "SELECT id, user_id, kind, body, status, created_at FROM security_reports"\n'
        "    if only_open:\n"
        "        q += \" WHERE status = 'open'\"\n"
        "    q += \" ORDER BY id DESC LIMIT ?\"\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(q, (limit,)).fetchall()\n"
        "    return [dict(r) for r in rows]\n\n"
        "def close_report(report_id: int) -> bool:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        '        cur = conn.execute("UPDATE security_reports SET status = \'closed\' WHERE id = ?", (report_id,))\n'
        "        conn.commit()\n"
        "        return cur.rowcount > 0\n\n"
        "def checklist() -> str:\n"
        "    return CHECKLIST\n\n"
        "def tips() -> str:\n"
        "    return TIPS\n\n"
        "def password_tips() -> str:\n"
        "    return PASSWORD_TIPS\n\n"
        "def dns_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /dns example.com'\n"
        "    lines = [f'DNS overview — {h}']\n"
        "    try:\n"
        "        infos = socket.getaddrinfo(h, None)\n"
        "        seen: set[str] = set()\n"
        "        for info in infos:\n"
        "            ip = info[4][0]\n"
        "            if ip in seen:\n"
        "                continue\n"
        "            seen.add(ip)\n"
        "            fam = 'AAAA' if ':' in ip else 'A'\n"
        "            lines.append(f'  {fam}: {ip}')\n"
        "            if len(seen) >= 8:\n"
        "                break\n"
        "        if not seen:\n"
        "            lines.append('  (no A/AAAA resolved)')\n"
        "    except socket.gaierror as exc:\n"
        "        lines.append(f'  resolve error: {exc}')\n"
        "    except Exception as exc:\n"
        "        lines.append(f'  error: {exc}')\n"
        "    lines.append('Note: passive lookup only (stdlib).')\n"
        "    return '\\n'.join(lines)\n\n"
        "def mx_check(host: str) -> str:\n"
        "    # Stdlib cannot query MX RRset without dnspython; give honest guidance + A lookup.\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /mx example.com'\n"
        "    base = dns_check(h)\n"
        "    return (\n"
        "        base + '\\n\\nMX tip: use dig/nslookup for MX/SPF/DMARC records. '\n"
        "        'This bot does passive A/AAAA only (no external DNS libs).'\n"
        "    )\n\n"
        "def tls_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /tls example.com'\n"
        "    try:\n"
        "        ctx = ssl.create_default_context()\n"
        "        with socket.create_connection((h, 443), timeout=8) as sock:\n"
        "            with ctx.wrap_socket(sock, server_hostname=h) as ssock:\n"
        "                cert = ssock.getpeercert()\n"
        "                ver = ssock.version()\n"
        "        subject = dict(x[0] for x in (cert or {}).get('subject', ()) )\n"
        "        issuer = dict(x[0] for x in (cert or {}).get('issuer', ()) )\n"
        "        not_after = (cert or {}).get('notAfter', '?')\n"
        "        cn = subject.get('commonName') or subject.get('organizationName') or '?'\n"
        "        iss = issuer.get('commonName') or issuer.get('organizationName') or '?'\n"
        "        return (\n"
        "            f'TLS overview — {h}\\n'\n"
        "            f'  protocol: {ver}\\n'\n"
        "            f'  subject CN: {cn}\\n'\n"
        "            f'  issuer: {iss}\\n'\n"
        "            f'  notAfter: {not_after}\\n'\n"
        "            'Passive certificate read only.'\n"
        "        )\n"
        "    except Exception as exc:\n"
        "        return f'TLS check failed for {h}: {exc}'\n\n"
        "def http_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /httpstatus example.com'\n"
        "    url = f'https://{h}/'\n"
        "    try:\n"
        "        req = Request(url, method='GET', headers={'User-Agent': 'SecBot/1.0'})\n"
        "        with urlopen(req, timeout=8) as resp:  # noqa: S310 — host validated\n"
        "            code = getattr(resp, 'status', None) or resp.getcode()\n"
        "            return f'HTTP {code} — {url}'\n"
        "    except Exception as exc:\n"
        "        return f'HTTP probe failed for {h}: {exc}'\n\n"
        "def headers_check(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /headers example.com'\n"
        "    url = f'https://{h}/'\n"
        "    interesting = (\n"
        "        'strict-transport-security', 'content-security-policy',\n"
        "        'x-frame-options', 'x-content-type-options', 'referrer-policy',\n"
        "        'permissions-policy', 'server',\n"
        "    )\n"
        "    try:\n"
        "        req = Request(url, method='GET', headers={'User-Agent': 'SecBot/1.0'})\n"
        "        with urlopen(req, timeout=8) as resp:  # noqa: S310\n"
        "            hdrs = {k.lower(): v for k, v in resp.headers.items()}\n"
        "        lines = [f'Security headers — {h}']\n"
        "        for key in interesting:\n"
        "            val = hdrs.get(key)\n"
        "            lines.append(f'  {key}: {val if val else \"(missing)\"}')\n"
        "        return '\\n'.join(lines)\n"
        "    except Exception as exc:\n"
        "        return f'Headers probe failed for {h}: {exc}'\n\n"
        "def domain_overview(host: str) -> str:\n"
        "    h = _clean_host(host)\n"
        "    if not h:\n"
        "        return 'أدخل نطاقًا صالحًا: /domainscan example.com'\n"
        "    parts = [\n"
        "        dns_check(h),\n"
        "        '',\n"
        "        tls_check(h),\n"
        "        '',\n"
        "        http_check(h),\n"
        "        '',\n"
        "        headers_check(h),\n"
        "    ]\n"
        "    return '\\n'.join(parts)\n"
    )




