"""Emit service modules for generated bots (split package)."""
from __future__ import annotations

from ..schema import BotSpec

def _emit_moderation() -> str:
    """Advanced group moderation: ranks, warns, protection, anti-raid, audit log."""
    return (
        "\"\"\"Moderation service — ranks, warns, protection, anti-raid, per-chat settings.\"\"\"\n"
        "from __future__ import annotations\n"
        "\n"
        "import re\n"
        "import time\n"
        "from collections import defaultdict\n"
        "from telegram import ChatPermissions\n"
        "from telegram.ext import ContextTypes\n"
        "\n"
        "from app.db import connect, init_db\n"
        "\n"
        "_flood_bucket: dict[tuple[int, int], list[float]] = defaultdict(list)\n"
        "_join_bucket: dict[int, list[float]] = defaultdict(list)\n"
        "\n"
        "ROLE_ORDER = {\"member\": 0, \"moderator\": 1, \"admin\": 2, \"owner\": 3}\n"
        "\n"
        "\n"
        "def ensure() -> None:\n"
        "    init_db()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS warns (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"count INTEGER NOT NULL DEFAULT 0, last_ts INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS admin_log (\"\n"
        "            \"id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, \"\n"
        "            \"admin_id INTEGER NOT NULL, action TEXT NOT NULL, target_id INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"detail TEXT NOT NULL DEFAULT '', ts INTEGER NOT NULL)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS chat_settings (\"\n"
        "            \"chat_id INTEGER PRIMARY KEY, \"\n"
        "            \"max_warns INTEGER NOT NULL DEFAULT 3, \"\n"
        "            \"warn_ttl_hours INTEGER NOT NULL DEFAULT 168, \"\n"
        "            \"anti_link INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_spam INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_flood INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"anti_raid INTEGER NOT NULL DEFAULT 1, \"\n"
        "            \"flood_limit INTEGER NOT NULL DEFAULT 6, \"\n"
        "            \"flood_window INTEGER NOT NULL DEFAULT 8, \"\n"
        "            \"raid_joins INTEGER NOT NULL DEFAULT 8, \"\n"
        "            \"raid_window INTEGER NOT NULL DEFAULT 20, \"\n"
        "            \"escalation TEXT NOT NULL DEFAULT 'warn,mute,kick,ban', \"\n"
        "            \"owner_id INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"leave_msg TEXT NOT NULL DEFAULT '', \"\n"
        "            \"leave_on INTEGER NOT NULL DEFAULT 0, \"\n"
        "            \"rules_on_join INTEGER NOT NULL DEFAULT 1)\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS chat_roles (\"\n"
        "            \"chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, \"\n"
        "            \"role TEXT NOT NULL DEFAULT 'member', \"\n"
        "            \"PRIMARY KEY (chat_id, user_id))\"\n"
        "        )\n"
        "        conn.execute(\n"
        "            \"CREATE TABLE IF NOT EXISTS forbidden_words (\"\n"
        "            \"chat_id INTEGER NOT NULL, word TEXT NOT NULL, \"\n"
        "            \"PRIMARY KEY (chat_id, word))\"\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def log_action(chat_id: int, admin_id: int, action: str, target_id: int = 0, detail: str = \"\") -> None:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO admin_log (chat_id, admin_id, action, target_id, detail, ts) VALUES (?, ?, ?, ?, ?, ?)\",\n"
        "            (int(chat_id), int(admin_id), action, int(target_id), (detail or \"\")[:300], int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def list_log(chat_id: int, limit: int = 15) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT action, admin_id, target_id, detail, ts FROM admin_log \"\n"
        "            \"WHERE chat_id = ? ORDER BY id DESC LIMIT ?\",\n"
        "            (int(chat_id), max(1, min(limit, 40))),\n"
        "        ).fetchall()\n"
        "    if not rows:\n"
        "        return \"لا أحداث في السجل\"\n"
        "    out = []\n"
        "    for r in rows:\n"
        "        ts = time.strftime(\"%Y-%m-%d %H:%M\", time.localtime(int(r[\"ts\"])))\n"
        "        out.append(f\"• [{ts}] {r['action']} by={r['admin_id']} target={r['target_id']} {r['detail']}\")\n"
        "    return \"\\n\".join(out)\n"
        "\n"
        "\n"
        "def get_settings(chat_id: int) -> dict:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\"SELECT * FROM chat_settings WHERE chat_id = ?\", (int(chat_id),)).fetchone()\n"
        "    if not row:\n"
        "        return {\n"
        "            \"max_warns\": 3, \"warn_ttl_hours\": 168,\n"
        "            \"anti_link\": 1, \"anti_spam\": 1, \"anti_flood\": 1, \"anti_raid\": 1,\n"
        "            \"flood_limit\": 6, \"flood_window\": 8, \"raid_joins\": 8, \"raid_window\": 20,\n"
        "            \"escalation\": \"warn,mute,kick,ban\", \"owner_id\": 0,\n"
        "            \"leave_msg\": \"\", \"leave_on\": 0, \"rules_on_join\": 1,\n"
        "        }\n"
        "    return dict(row)\n"
        "\n"
        "\n"
        "def _upsert_settings(chat_id: int, **fields) -> None:\n"
        "    ensure()\n"
        "    cur = get_settings(chat_id)\n"
        "    cur.update({k: v for k, v in fields.items() if v is not None})\n"
        "    vals = (\n"
        "        int(chat_id),\n"
        "        int(cur[\"max_warns\"]), int(cur[\"warn_ttl_hours\"]),\n"
        "        int(cur[\"anti_link\"]), int(cur[\"anti_spam\"]), int(cur[\"anti_flood\"]), int(cur[\"anti_raid\"]),\n"
        "        int(cur[\"flood_limit\"]), int(cur[\"flood_window\"]), int(cur[\"raid_joins\"]), int(cur[\"raid_window\"]),\n"
        "        str(cur.get(\"escalation\") or \"warn,mute,kick,ban\"),\n"
        "        int(cur.get(\"owner_id\") or 0),\n"
        "        str(cur.get(\"leave_msg\") or \"\")[:500],\n"
        "        int(cur.get(\"leave_on\") or 0),\n"
        "        int(cur.get(\"rules_on_join\") if cur.get(\"rules_on_join\") is not None else 1),\n"
        "    )\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO chat_settings (\"\n"
        "            \"chat_id, max_warns, warn_ttl_hours, anti_link, anti_spam, anti_flood, anti_raid, \"\n"
        "            \"flood_limit, flood_window, raid_joins, raid_window, escalation, owner_id, \"\n"
        "            \"leave_msg, leave_on, rules_on_join) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) \"\n"
        "            \"ON CONFLICT(chat_id) DO UPDATE SET \"\n"
        "            \"max_warns=excluded.max_warns, warn_ttl_hours=excluded.warn_ttl_hours, \"\n"
        "            \"anti_link=excluded.anti_link, anti_spam=excluded.anti_spam, \"\n"
        "            \"anti_flood=excluded.anti_flood, anti_raid=excluded.anti_raid, \"\n"
        "            \"flood_limit=excluded.flood_limit, flood_window=excluded.flood_window, \"\n"
        "            \"raid_joins=excluded.raid_joins, raid_window=excluded.raid_window, \"\n"
        "            \"escalation=excluded.escalation, owner_id=excluded.owner_id, \"\n"
        "            \"leave_msg=excluded.leave_msg, leave_on=excluded.leave_on, \"\n"
        "            \"rules_on_join=excluded.rules_on_join\",\n"
        "            vals,\n"
        "        )\n"
        "        conn.commit()\n"
        "\n"
        "\n"
        "def set_max_warns(chat_id: int, n: int) -> str:\n"
        "    n = max(1, min(int(n), 20))\n"
        "    _upsert_settings(chat_id, max_warns=n)\n"
        "    return f\"حد التحذيرات أصبح {n}\"\n"
        "\n"
        "\n"
        "def set_protection(\n"
        "    chat_id: int,\n"
        "    anti_link: int | None = None,\n"
        "    anti_spam: int | None = None,\n"
        "    anti_flood: int | None = None,\n"
        "    anti_raid: int | None = None,\n"
        ") -> str:\n"
        "    fields = {}\n"
        "    if anti_link is not None:\n"
        "        fields[\"anti_link\"] = 1 if anti_link else 0\n"
        "    if anti_spam is not None:\n"
        "        fields[\"anti_spam\"] = 1 if anti_spam else 0\n"
        "    if anti_flood is not None:\n"
        "        fields[\"anti_flood\"] = 1 if anti_flood else 0\n"
        "    if anti_raid is not None:\n"
        "        fields[\"anti_raid\"] = 1 if anti_raid else 0\n"
        "    if fields:\n"
        "        _upsert_settings(chat_id, **fields)\n"
        "    s = get_settings(chat_id)\n"
        "    return (\n"
        "        f\"الحماية: روابط={'تشغيل' if s['anti_link'] else 'إيقاف'} | \"\n"
        "        f\"سبام={'تشغيل' if s['anti_spam'] else 'إيقاف'} | \"\n"
        "        f\"فيض={'تشغيل' if s['anti_flood'] else 'إيقاف'} | \"\n"
        "        f\"غارة={'تشغيل' if s['anti_raid'] else 'إيقاف'}\"\n"
        "    )\n"
        "\n"
        "\n"
        "def set_owner(chat_id: int, user_id: int) -> str:\n"
        "    _upsert_settings(chat_id, owner_id=int(user_id))\n"
        "    set_role(chat_id, int(user_id), \"owner\")\n"
        "    return f\"تم تعيين Owner: {user_id}\"\n"
        "\n"
        "\n"
        "def get_role(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    s = get_settings(chat_id)\n"
        "    if int(s.get(\"owner_id\") or 0) == int(user_id):\n"
        "        return \"owner\"\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT role FROM chat_roles WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    return str(row[\"role\"]) if row else \"member\"\n"
        "\n"
        "\n"
        "def set_role(chat_id: int, user_id: int, role: str) -> str:\n"
        "    role = (role or \"member\").lower().strip()\n"
        "    if role not in ROLE_ORDER:\n"
        "        role = \"member\"\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT INTO chat_roles (chat_id, user_id, role) VALUES (?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET role = excluded.role\",\n"
        "            (int(chat_id), int(user_id), role),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"رتبة {user_id}: {role}\"\n"
        "\n"
        "\n"
        "def can_act(chat_id: int, actor_id: int, target_id: int, min_role: str = \"moderator\") -> tuple[bool, str]:\n"
        "    actor_role = get_role(chat_id, actor_id)\n"
        "    target_role = get_role(chat_id, target_id)\n"
        "    if target_role == \"owner\" and actor_role != \"owner\":\n"
        "        return False, \"لا يمكن المساس بالـ Owner\"\n"
        "    if ROLE_ORDER.get(actor_role, 0) < ROLE_ORDER.get(min_role, 1):\n"
        "        return False, f\"صلاحيتك ({actor_role}) أقل من المطلوب ({min_role})\"\n"
        "    if int(actor_id) != int(target_id) and ROLE_ORDER.get(actor_role, 0) <= ROLE_ORDER.get(target_role, 0):\n"
        "        if actor_role != \"owner\":\n"
        "            return False, \"لا يمكنك تنفيذ إجراء على رتبة مساوية أو أعلى\"\n"
        "    return True, \"ok\"\n"
        "\n"
        "\n"
        "def is_owner_protected(chat_id: int, user_id: int) -> bool:\n"
        "    return get_role(chat_id, user_id) == \"owner\"\n"
        "\n"
        "\n"
        "def list_forbidden(chat_id: int) -> list[str]:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        rows = conn.execute(\n"
        "            \"SELECT word FROM forbidden_words WHERE chat_id = ? ORDER BY word\",\n"
        "            (int(chat_id),),\n"
        "        ).fetchall()\n"
        "    return [str(r[\"word\"]) for r in rows]\n"
        "\n"
        "\n"
        "def add_forbidden(chat_id: int, word: str) -> str:\n"
        "    w = (word or \"\").strip().lower()\n"
        "    if not w or len(w) > 64:\n"
        "        return \"كلمة غير صالحة\"\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"INSERT OR IGNORE INTO forbidden_words (chat_id, word) VALUES (?, ?)\",\n"
        "            (int(chat_id), w),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"أُضيفت للكلمات الممنوعة: {w}\"\n"
        "\n"
        "\n"
        "def remove_forbidden(chat_id: int, word: str) -> str:\n"
        "    w = (word or \"\").strip().lower()\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"DELETE FROM forbidden_words WHERE chat_id = ? AND word = ?\",\n"
        "            (int(chat_id), w),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"حُذفت من الممنوعة: {w}\"\n"
        "\n"
        "\n"
        "def has_forbidden(chat_id: int, text: str) -> str | None:\n"
        "    words = list_forbidden(chat_id)\n"
        "    if not words:\n"
        "        return None\n"
        "    t = (text or \"\").lower()\n"
        "    for w in words:\n"
        "        if w and w in t:\n"
        "            return w\n"
        "    return None\n"
        "\n"
        "\n"
        "def _purge_expired_warns(chat_id: int, user_id: int) -> None:\n"
        "    s = get_settings(chat_id)\n"
        "    ttl = max(1, int(s.get(\"warn_ttl_hours\") or 168)) * 3600\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count, last_ts FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        if not row:\n"
        "            return\n"
        "        if int(row[\"last_ts\"] or 0) and (time.time() - int(row[\"last_ts\"])) > ttl:\n"
        "            conn.execute(\n"
        "                \"UPDATE warns SET count = 0, last_ts = 0 WHERE chat_id = ? AND user_id = ?\",\n"
        "                (int(chat_id), int(user_id)),\n"
        "            )\n"
        "            conn.commit()\n"
        "\n"
        "\n"
        "def get_warns(chat_id: int, user_id: int) -> int:\n"
        "    _purge_expired_warns(chat_id, user_id)\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "    return int(row[\"count\"]) if row else 0\n"
        "\n"
        "\n"
        "def clear_warnings(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"DELETE FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تم مسح تحذيرات {user_id}\"\n"
        "\n"
        "\n"
        "def unwarn_user(chat_id: int, user_id: int) -> str:\n"
        "    ensure()\n"
        "    n = get_warns(chat_id, user_id)\n"
        "    if n <= 0:\n"
        "        return \"لا توجد تحذيرات\"\n"
        "    with connect() as conn:\n"
        "        conn.execute(\n"
        "            \"UPDATE warns SET count = ? WHERE chat_id = ? AND user_id = ?\",\n"
        "            (n - 1, int(chat_id), int(user_id)),\n"
        "        )\n"
        "        conn.commit()\n"
        "    return f\"تحذيرات {user_id}: {n - 1}\"\n"
        "\n"
        "\n"
        "async def _apply_escalation(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, count: int) -> str:\n"
        "    s = get_settings(chat_id)\n"
        "    max_w = max(1, int(s.get(\"max_warns\") or 3))\n"
        "    steps = [x.strip() for x in str(s.get(\"escalation\") or \"warn,mute,kick,ban\").split(\",\") if x.strip()]\n"
        "    if count < max_w:\n"
        "        return f\"تحذير {count}/{max_w}\"\n"
        "    action = steps[min(len(steps) - 1, max(0, count - max_w))] if steps else \"mute\"\n"
        "    if action == \"mute\":\n"
        "        await mute_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: كتم (تحذيرات={count})\"\n"
        "    if action == \"kick\":\n"
        "        await kick_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: طرد (تحذيرات={count})\"\n"
        "    if action == \"ban\":\n"
        "        await ban_user(context, chat_id, user_id)\n"
        "        return f\"تصعيد: حظر (تحذيرات={count})\"\n"
        "    return f\"تحذير {count}/{max_w}\"\n"
        "\n"
        "\n"
        "async def warn_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, admin_id: int = 0) -> str:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return \"لا يمكن تحذير الـ Owner\"\n"
        "    if admin_id:\n"
        "        ok, reason = can_act(chat_id, admin_id, user_id, \"moderator\")\n"
        "        if not ok:\n"
        "            return reason\n"
        "    ensure()\n"
        "    _purge_expired_warns(chat_id, user_id)\n"
        "    with connect() as conn:\n"
        "        row = conn.execute(\n"
        "            \"SELECT count FROM warns WHERE chat_id = ? AND user_id = ?\",\n"
        "            (int(chat_id), int(user_id)),\n"
        "        ).fetchone()\n"
        "        n = (int(row[\"count\"]) if row else 0) + 1\n"
        "        conn.execute(\n"
        "            \"INSERT INTO warns (chat_id, user_id, count, last_ts) VALUES (?, ?, ?, ?) \"\n"
        "            \"ON CONFLICT(chat_id, user_id) DO UPDATE SET count = excluded.count, last_ts = excluded.last_ts\",\n"
        "            (int(chat_id), int(user_id), n, int(time.time())),\n"
        "        )\n"
        "        conn.commit()\n"
        "    if admin_id:\n"
        "        log_action(chat_id, admin_id, \"warn\", user_id, f\"count={n}\")\n"
        "    return await _apply_escalation(context, chat_id, user_id, n)\n"
        "\n"
        "\n"
        "async def ban_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.ban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def unban_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    await context.bot.unban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def mute_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int, seconds: int = 3600) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    until = int(time.time()) + max(30, int(seconds))\n"
        "    perms = ChatPermissions(can_send_messages=False)\n"
        "    await context.bot.restrict_chat_member(chat_id=chat_id, user_id=user_id, permissions=perms, until_date=until)\n"
        "\n"
        "\n"
        "async def unmute_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    perms = ChatPermissions(\n"
        "        can_send_messages=True, can_send_media_messages=True,\n"
        "        can_send_other_messages=True, can_add_web_page_previews=True,\n"
        "    )\n"
        "    await context.bot.restrict_chat_member(chat_id=chat_id, user_id=user_id, permissions=perms)\n"
        "\n"
        "\n"
        "async def kick_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.ban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "    await context.bot.unban_chat_member(chat_id=chat_id, user_id=user_id)\n"
        "\n"
        "\n"
        "async def promote_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    await context.bot.promote_chat_member(\n"
        "        chat_id=chat_id, user_id=user_id,\n"
        "        can_delete_messages=True, can_restrict_members=True,\n"
        "        can_invite_users=True, can_pin_messages=True, can_promote_members=False,\n"
        "    )\n"
        "    set_role(chat_id, user_id, \"admin\")\n"
        "\n"
        "\n"
        "async def demote_user(context: ContextTypes.DEFAULT_TYPE, chat_id: int, user_id: int) -> None:\n"
        "    if is_owner_protected(chat_id, user_id):\n"
        "        return\n"
        "    await context.bot.promote_chat_member(\n"
        "        chat_id=chat_id, user_id=user_id,\n"
        "        can_delete_messages=False, can_restrict_members=False,\n"
        "        can_invite_users=False, can_pin_messages=False, can_promote_members=False,\n"
        "    )\n"
        "    set_role(chat_id, user_id, \"member\")\n"
        "\n"
        "\n"
        "async def pin_message(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.pin_chat_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "async def delete_message(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.delete_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "async def purge(context: ContextTypes.DEFAULT_TYPE, chat_id: int, message_id: int) -> None:\n"
        "    await context.bot.delete_message(chat_id=chat_id, message_id=message_id)\n"
        "\n"
        "\n"
        "def slowmode_info() -> str:\n"
        "    return \"الوضع البطيء يُضبط من إعدادات تيليجرام للجروب أو عبر صلاحيات البوت إن توفرت.\"\n"
        "\n"
        "\n"
        "def user_info(user_id: int, chat_id: int = 0) -> str:\n"
        "    role = get_role(chat_id, user_id) if chat_id else \"member\"\n"
        "    warns = get_warns(chat_id, user_id) if chat_id else 0\n"
        "    return f\"المعرف: {user_id}\\nالرتبة: {role}\\nالتحذيرات: {warns}\"\n"
        "\n"
        "\n"
        "def looks_like_link(text: str) -> bool:\n"
        "    t = (text or \"\").lower()\n"
        "    return (\"http://\" in t) or (\"https://\" in t) or (\"t.me/\" in t) or (\"www.\" in t)\n"
        "\n"
        "\n"
        "def looks_like_spam(text: str) -> bool:\n"
        "    t = (text or \"\").strip()\n"
        "    if len(t) > 800:\n"
        "        return True\n"
        "    if t and len(set(t)) <= 2 and len(t) >= 12:\n"
        "        return True\n"
        "    if len(re.findall(r\"(.)\\1{6,}\", t)) >= 1:\n"
        "        return True\n"
        "    return False\n"
        "\n"
        "\n"
        "def record_message_flood(chat_id: int, user_id: int) -> bool:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"anti_flood\") or 0):\n"
        "        return False\n"
        "    now = time.time()\n"
        "    window = max(3, int(s.get(\"flood_window\") or 8))\n"
        "    limit = max(3, int(s.get(\"flood_limit\") or 6))\n"
        "    key = (int(chat_id), int(user_id))\n"
        "    bucket = [t for t in _flood_bucket[key] if now - t <= window]\n"
        "    bucket.append(now)\n"
        "    _flood_bucket[key] = bucket\n"
        "    return len(bucket) > limit\n"
        "\n"
        "\n"
        "def record_join(chat_id: int) -> bool:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"anti_raid\") or 0):\n"
        "        return False\n"
        "    now = time.time()\n"
        "    window = max(5, int(s.get(\"raid_window\") or 20))\n"
        "    limit = max(3, int(s.get(\"raid_joins\") or 8))\n"
        "    bucket = [t for t in _join_bucket[int(chat_id)] if now - t <= window]\n"
        "    bucket.append(now)\n"
        "    _join_bucket[int(chat_id)] = bucket\n"
        "    return len(bucket) > limit\n"
        "\n"
        "\n"
        "def set_leave_message(chat_id: int, text: str, enabled: int = 1) -> str:\n"
        "    _upsert_settings(chat_id, leave_msg=(text or \"\")[:500], leave_on=1 if enabled else 0)\n"
        "    return \"تم تحديث رسالة المغادرة\"\n"
        "\n"
        "\n"
        "def get_leave_message(chat_id: int) -> str:\n"
        "    s = get_settings(chat_id)\n"
        "    if not int(s.get(\"leave_on\") or 0):\n"
        "        return \"\"\n"
        "    return str(s.get(\"leave_msg\") or \"\")\n"
    )



