"""Build immutable Docker images for generated bots (no host bind-mount of source).

Architecture shift:
  - Source is COPIED into the image at build time
  - Runtime container starts from the image only (stateless host disk for code)
  - Image tag is content-addressable: tbe/u{user}/{name}:{sha12}
  - Optional push to registry (TBE_DOCKER_REGISTRY) enables multi-node pull

This is the foundation for horizontal scaling: any node that can pull the
image can run the bot without the original OUTPUT_DIR tree.
"""
from __future__ import annotations

import hashlib
import logging
import os
import re
import subprocess
import textwrap
from pathlib import Path
from typing import Optional

logger = logging.getLogger("tbe.bot_image_builder")

_DOCKERFILE = """\
# Auto-generated by capability_maestro — do not edit by hand for production deploys
FROM {base_image}
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    HOME=/tmp \\
    PYTHONPATH=/app
WORKDIR /app
# Non-root user
RUN useradd -u 10001 -m -s /usr/sbin/nologin botuser || true
COPY requirements.txt /app/requirements.txt
RUN if [ -f /app/requirements.txt ]; then \\
      pip install --no-cache-dir --only-binary=:all: -r /app/requirements.txt || \\
      pip install --no-cache-dir -r /app/requirements.txt || true; \\
    fi
COPY . /app
RUN chown -R 10001:10001 /app || true
USER 10001:10001
CMD [\"python\", \"-u\", \"{entry}\"]
"""


def _safe(s: str, n: int = 40) -> str:
    s = re.sub(r"[^a-zA-Z0-9_.-]+", "-", (s or "x")).strip("-").lower()
    return (s or "x")[:n]


def content_hash(project_path: Path) -> str:
    h = hashlib.sha256()
    for p in sorted(project_path.rglob("*")):
        if not p.is_file():
            continue
        if any(x in p.parts for x in (".git", "__pycache__", ".venv", "venv")):
            continue
        if p.suffix in {".pyc", ".log", ".zip"}:
            continue
        if p.name in {".tbe_bot_token", ".env", ".tbe_smoke_runner.py"}:
            continue
        try:
            h.update(p.relative_to(project_path).as_posix().encode())
            h.update(p.read_bytes())
        except Exception:
            continue
    return h.hexdigest()[:12]


def write_dockerfile(project_path: Path, *, entry: str = "main.py") -> Path:
    base = (os.environ.get("TBE_DOCKER_IMAGE") or "python:3.11-slim").strip()
    entry_rel = entry if not entry.startswith("/") else Path(entry).name
    if not (project_path / entry_rel).is_file():
        for cand in ("main.py", "bot.py", "app.py"):
            if (project_path / cand).is_file():
                entry_rel = cand
                break
    text = _DOCKERFILE.format(base_image=base, entry=entry_rel)
    df = project_path / "Dockerfile"
    df.write_text(text, encoding="utf-8")
    # Ensure requirements exists
    req = project_path / "requirements.txt"
    if not req.is_file():
        req.write_text("python-telegram-bot>=21.0,<22\n", encoding="utf-8")
    else:
        try:
            from telegram_bot_engine.services.requirements_policy import sanitize_requirements_text
            cleaned, _ = sanitize_requirements_text(req.read_text(encoding="utf-8", errors="ignore"))
            req.write_text(cleaned, encoding="utf-8")
        except Exception:
            pass
    return df


def image_tag_for(project_path: Path, user_id: str | int) -> str:
    registry = (os.environ.get("TBE_DOCKER_REGISTRY") or "").strip().rstrip("/")
    name = _safe(project_path.name, 32)
    tag = f"tbe/u{_safe(str(user_id), 16)}/{name}:{content_hash(project_path)}"
    if registry:
        return f"{registry}/{tag}"
    return tag


def build_image(
    project_path: Path,
    *,
    user_id: str | int,
    entry: str = "main.py",
    timeout: int = 600,
) -> tuple[bool, str, str]:
    """Build image. Returns (ok, image_tag_or_error, log_tail)."""
    path = Path(project_path).resolve()
    if not path.is_dir():
        return False, "project_missing", ""
    write_dockerfile(path, entry=entry)
    tag = image_tag_for(path, user_id)
    # Skip rebuild if image already present with same tag
    insp = subprocess.run(
        ["docker", "image", "inspect", tag],
        capture_output=True, text=True, timeout=30, check=False,
    )
    if insp.returncode == 0:
        return True, tag, "image_cached"
    cmd = ["docker", "build", "-t", tag, "-f", str(path / "Dockerfile"), str(path)]
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout, check=False,
        )
    except subprocess.TimeoutExpired:
        return False, "build_timeout", ""
    except Exception as e:
        return False, f"build_error:{type(e).__name__}", str(e)[:200]
    log = ((proc.stdout or "") + "\n" + (proc.stderr or "")).strip()
    if proc.returncode != 0:
        return False, f"build_failed:{proc.returncode}", log[-800:]
    # Optional registry push for multi-node
    if (os.environ.get("TBE_DOCKER_PUSH") or "").strip().lower() in {"1", "true", "yes", "on"}:
        push = subprocess.run(
            ["docker", "push", tag], capture_output=True, text=True, timeout=300, check=False,
        )
        if push.returncode != 0:
            logger.warning("docker push failed for %s: %s", tag, (push.stderr or "")[:200])
        else:
            log += "\npush_ok"
    return True, tag, log[-400:]
